### ISSUE TITLE
Decorators for collections - question

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#100]
I'm developing a set of icon overlays, to show the following boolean attributes:
- has precedents (it was calculated from another resource)
- has dependents (it is used to calculate another resource)

See the section on "Icon Overlays" in this document:
http://www.eclipse.org/articles/Article-UI-Guidelines/Contents.html

(note the "Java Overlay" section includes 3 overlays to the right of the icon)

Here's an article on how to implement decorators:
http://www.eclipse.org/articles/Article-Decorators/decorators.html

Here are my thoughts on how to use the overlays:
![icon design](https://docs.google.com/drawings/d/11z818QD5uyrd8pHelkDoX1FNX2ekMfI3DskXDI__kdA/pub?w=960&h=720)

Are you familiar with how to produce these icon overlays?  Do you have any feedback on the strategy?

**Comment by pecko** [comment]
I suppose that you want to add image overlays (decorators) to tree control in Data Manager editor, I have worked with that stuff and can do it if you provide icons.

BTW this is jubilee issue (100).

**Comment by IanMayo** [comment]
#100 :cake: :cake: :cake: !

**Comment by IanMayo** [comment]
@pecko - looks like I closed this issue by mistake.

[composite_png.zip | uploaded via ZenHub](https://files.zenhub.io/56323b4ffa755c5d4d58b24b)

LimpetLabelProvider will need to be extended to support the new set of composite icons (attached).

For collections we'll be option 2 in the diagram above.

**Comment by pecko** [comment]
You can tell me when I can start on this.

**Comment by IanMayo** [comment]
You can start it today :-)

Message sent in Hangouts 30 mins ago.

**Comment by pecko** [comment]
i have created base decorator. It is in branch: https://github.com/pecko/limpet/tree/issue100
There isn't a PR yet.

![decorator](https://cloud.githubusercontent.com/assets/534584/10860452/8daf55e4-7f68-11e5-9394-5934d8ae60f1.png)

The decorator works in the following way:
- top-right angle is direction (in/out or both)
- bottom-right is time (if object is temporal)
- bottom-left is quantity (if object is quantity)

I have created time_dec.png and quantity_dec.png (scaled to 7x8 pt), 
Not sure how to recognize speed, length and other data and will I decorate icon and set a new one for a different data.
We can add main icon for object and 4 overlays (top-left, top-right, bottom-left and bottom-right). 

Please review and advice!

**Comment by IanMayo** [comment]
Have made some changes in this branch:
https://github.com/debrief/limpet/tree/issue100_icons_temp

[sometime, could you give me write permission to your repo, then I can make changes/fixes to your branches].

I'd appreciate you looking at, and tidying/correcting my changes.

Are you able to layout the 3 decorator icons like in the screen mockup at the top of this issue?  Aah no, the current API doesn't allow it.  Ok.

I guess this issue will be complete, until I get some more icons.

**Comment by pecko** [comment]
> I'd appreciate you looking at, and tidying/correcting my changes.

I have done it.

> Are you able to layout the 3 decorator icons like in the screen mockup at the top of this issue? Aah no, the current API doesn't allow it. Ok.

We can set 5 icons for each objects: 1 main icon 16X16 in limpet label providers and 4 decorator icons 7x8 in angles (top-left, top-right, bottom-left, bottom-right.

> I'd appreciate you looking at, and tidying/correcting my changes.

I have cherry-pick your commits and create the PR: https://github.com/debrief/limpet/pull/135

**Comment by IanMayo** [comment]
Technical proof implemented. Should be easy to extend for other images.

**Comment by IanMayo** [comment]
Done.
