### ISSUE TITLE
Improve welcome page

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#101]
We have a welcome page, but it is currently blank.

I wish to provide some introductory text/guidance in the welcome view.  We've got 4 sub-pages in the Debrief welcome.  Could you give us a welcome page, plus two other pages:  "Getting started" and "About"?  If you put some "boilerplate" text on each page, I can modify that to show my content.

**Comment by pecko** [comment]
I have created the PR: https://github.com/debrief/limpet/pull/216
The xhtml/css files (root.xhtml, gettingstarted.xhtml, about.xhtml, root.css, shared.css) are in the info.limpet.rcp/content directory.

Notice:
If you use Linux, you should install webkit or xulrunner. I have used webkit on Ubuntu 15.04 installed with:

```
sudo apt-get install libwebkit-dev
```

Limpet will silently show empty page if you haven't installed compatible browser.

**Comment by pecko** [comment]
Screenshot:
![limpet](https://cloud.githubusercontent.com/assets/534584/12010948/926c94a4-acbb-11e5-9a9a-546a855ff853.png)

**Comment by IanMayo** [comment]
good advice.  I rebuilt my machine a month or so ago, and hadn't done this step. I'm sure this will fix it for ubuntu.

**Comment by pecko** [comment]
Eclipse/Limpet can crash with webkit on some distribution (Ubuntu 14.04, for instance), because SWT from Eclipse 3.8 isn't compatible with some webkit versions. In this case, solution is xulrunner.
