### ISSUE TITLE
UI Tidying

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#102]
@pecko  - this issue is for the future, I'm just using it to collect UI thoughts
## Views
- CoreAnalysisView - when "Sync with editor" is selected in a view, we should retrieve the selection from the current editor (if open), and display it.
- Editor closing - if a view is showing data based on an editor, it should clear when that editor is closed.

**Comment by pecko** [comment]
It id doable relative easily.
Probably also the following:
- editor should valid title (file name)
- title would be changed if user change file name in navigator
- editor would be closed if user remove file to navigator

**Comment by pecko** [comment]
We would probably add the Save As action.

**Comment by pecko** [comment]
We would also refresh project after saving.

**Comment by IanMayo** [comment]
Yes - we do need to refresh the project after saving. Could you produce a PR?

**Comment by pecko** [comment]
I will create the PR today.

**Comment by IanMayo** [comment]
I'd also appreciate you implementing the **Save As** functionality,  please.

**Comment by pecko** [comment]
Of course. What about implementing search (by name) using FilteredTree?

**Comment by IanMayo** [comment]
No, let's not bother with that right now.

**Comment by pecko** [comment]
> CoreAnalysisView - when "Sync with editor" is selected in a view, we should retrieve the selection from the current editor (if open), and display it.

Seems, this feature is already implemented.

> Editor closing - if a view is showing data based on an editor, it should clear when that editor is closed.

I have just implemented this feature for CoreAnalysisView(s). Will I add it to XYPlot and Range Slider, too?

**Comment by IanMayo** [comment]
For now, could you just do **Save As**, and **Refresh Project on Save**?

**Comment by pecko** [comment]
OK. Since I have implemented selection on CoreAnalysisView when closing a editor (from issue description) I will keep it.
I will also fix ugly NPE in XYPlot and DataFrequency view described in https://github.com/debrief/limpet/issues/199

**Comment by pecko** [comment]
The PR: https://github.com/debrief/limpet/pull/200

**Comment by pecko** [comment]
I have also added the following:
- change editor title if user change file name in navigator
- close editor if user remove file to navigator
