### ISSUE TITLE
Tidy layout of range slider

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#107]
I've implemented the range slider view.  It's pretty poor.

I'd like it to have this layout:
![range slider layout](https://docs.google.com/drawings/d/1eY7bdXan1DK1a8i1e5uiswfhp2H9n499NLVILMtOtAg/pub?w=960&h=720)

**Comment by pecko** [comment]
@IanMayo 

Could you, please, apply your work to the master branch? Or I will do it in your branch?

**Comment by IanMayo** [comment]
merged - was waiting for green light from Mr Travis

**Comment by pecko** [comment]
I suppose you want something like this:

![image](https://cloud.githubusercontent.com/assets/534584/10258523/36432778-695f-11e5-9d59-4e68b30da02b.png)

**Comment by pecko** [comment]
The PR: https://github.com/debrief/limpet/pull/108

**Comment by IanMayo** [comment]
perfect

**Comment by pecko** [comment]
The PR applied.
