### ISSUE TITLE
Range Slider view doesn't change

### ISSUE THREAD

**Issue by pecko** [debrief/limpet#119]
Steps to reproduce:
- open a data manager editor
- create sample data
- click Ranged Speed Singleton

The Range Slider view doesn't change.

@IanMayo 

I can see that a range for this collection is null, but not sure how you introduce it.

![image](https://cloud.githubusercontent.com/assets/534584/10351398/a0aacb46-6d49-11e5-9cd7-01425d0e9030.png)

**Comment by IanMayo** [comment]
Thanks for reporting that Peco,
it was related to making the helper classes persistent - which meant the range wasn't getting stored to XML file.

Fixed in #121
