### ISSUE TITLE
Tidy project build

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#12]
I've created a package structure:
https://docs.google.com/presentation/d/1imOVCf2A3RcmF2BCb_QlSupFcr4q31r0A1cYdB1iqGo/pub?start=false&loop=false&delayms=3000&slide=id.ge0b1e5936_2_0

You'll see that I'm breaking Limpet into 2 components - core and RCP.

But, the core project isn't packaged in a way that I can refer to it from the info.limpet.rcp package.  The code that fails is in info.limpet.rcp/DataModel.java.  I guess we need to convert it into an OSGI bundle

So, I'd like your support in these tasks:
- convert the info.limpet project into a form that it can be seen from the info.limpet.rcp project  (I guess it will be an OSGI bundle)
- ensure the jars in info.limpet.lib are visible to the info.limpet.rcp project

Hmm, should we do this by converting them to Maven projects?

**Comment by pecko** [comment]
> The code that fails is in info.limpet.rcp/DataModel.java

You mean
https://github.com/debrief/limpet/blob/master/info.limpet.rcp/src/info/limpet/rcp/data_provider/data/DataModel.java

**Comment by IanMayo** [comment]
yes

**Comment by pecko** [comment]
I propose to separate JUnit Tests to a separate plugin.
We don't need tests when using info.limpet.

I think that we should move all libraries to separate plugin. It will be easier to maintain them.

Also, I suppose that we want keep the info.limpet plugin name.

**Comment by IanMayo** [comment]
Yes, that's all fine.

**Comment by pecko** [comment]
Versions: We will start with 1.0.0
Provider: MWC

Plugins:
info.limpet.libs - Required libraries
info.limpet - Limpet Core
info.limpet.test - Limpet Test
info.limpet.rcp - Limpet RCP

Features:
1) info.limpet.feature includes
- info.limpet.libs - Required libraries
- info.limpet - Limpet Core

2) info.limpet.test.features includes
- info.limpet.test - Limpet Test

3) info.limpet.rcp.feature includes
- info.limpet.feature
- info.limpet.rcp plugin

Agree?

**Comment by pecko** [comment]
and very important

target platform: eclipse 3.8 still. Right?

**Comment by IanMayo** [comment]
Yes, that's all correct.

**Comment by pecko** [comment]
We will need icon for feature (32x32 or bigger). I will use debrief icon for now.

**Comment by pecko** [comment]
I will set JRE 1.8 dependencies for the info.limpet.rcp plugin because it uses java.util.stream.Stream.
Other plugins requires 1.7.

**Comment by IanMayo** [comment]
Can you remove the 1.8 requirement from RCP?

**Comment by pecko** [comment]
We have to remove java.util.stream.Stream usage from https://github.com/debrief/limpet/blob/master/info.limpet.rcp/src/info/limpet/rcp/data_provider/data/DataModel.java

**Comment by pecko** [comment]
BTW
I have used tycho 0.23.1. Maybe we could upgrade in Debrief, too.

**Comment by IanMayo** [comment]
Removing stream is fine.  The IDE inserted the methods.

**Comment by pecko** [comment]
You mean remove import and all usage? You will add what is necessary with JDK 1.7?

**Comment by IanMayo** [comment]
I don't need to use the Stream class at all.  So, I won't need to replace it.

**Comment by pecko** [comment]
OK. I will remove import and methods stream and parallelStream and revert plugins to 1.8.

BTW
It's almost finished. I have just the issue with test. It want to start intro (browser) that is webkit by default and doesn't work on 3.8

**Comment by pecko** [comment]
The PR: https://github.com/debrief/limpet/pull/25

To build you should do the following:

cd info.limpet.targetplatforms
mvn clean install

Installing target platform should be done only when it is changed.

cd ..
mvn clean verify -U -B -fae
or just
mvn clean install

The build will create bundles (info.limpet/libs, info.limpet, info.limpet.rcp), run tests and create update site.

The build can be run on travis.

**Comment by pecko** [comment]
The update site is placed in  info.limpet.site/target/site-0.0.1-SNAPSHOT.zip
You can unpack and test it locally.

**Comment by pecko** [comment]
I didn't create the info.limpet.test.feature feature. It isn't required for running tests. We don't have any test feature in Debrief too.

**Comment by IanMayo** [comment]
Sorted.
