### ISSUE TITLE
InMemoryStore.java requires Java 8

### ISSUE THREAD

**Issue by pecko** [debrief/limpet#122]
This class imports (unnecessarily) java.util.stream.Stream that there is only in Java 8 class.
See https://github.com/debrief/limpet/blob/master/info.limpet/src/info/limpet/data/store/InMemoryStore.java#L12

**Comment by IanMayo** [comment]
Sure I fixed it in the branch, via the GitHub web page:
https://github.com/debrief/limpet/commit/f9aab6c0e4ef7f4d47b14735df0f21e7d7b8031c
