### ISSUE TITLE
Reduce storage size

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#129]
The method we use to store quantity data is too verbose. 80Kb of CSV data can take 4Mb of XML file.

We have two options:
- change the internal storage format for Quantity data to be doubles rather than Quantities
- provide a custom Xstream import/export format that just stores a double
- [x] investigate custom Xstream converters, and decide on the best strategy.

**Comment by IanMayo** [comment]
@pecko  - I'd like to assign this to you, please.

The values collection of QuantityColllection takes up lots of space. Could you provide some "converter" function for XStream that represents the values as an array of doubles?  

I'd like this code to sit inside QuantityCollection if possible, since we will use it for Debrief persistence (which won't be using XSTream).

Oh, and could we also reduce the storage space of TemporalCollections, by storing XML Dates instead of the current objects?

Hmm, maybe these capabilities would sit in TemporalHelper and QuantityHelper.  Maybe...

**Comment by pecko** [comment]
Probably not too important, but can you attach some test bigger CSV (80Kb of CSV data)?

**Comment by pecko** [comment]
I have created the issue129 branch (https://github.com/pecko/limpet/tree/issue129).

It will persist all collections containing Measure objects as simple double (+ one element for unit). 
I have to create a marker class (LimpetList; just extends ArrayList). If it isn't acceptable, I can try another way, but seems not too easy.
The code is in LimpetCollectionConverter - use XStream converter feature.
The size is reduced cca 30%.

Maybe, we could also change storage for Point.

The code is tricky and require testing. I still haven't created the PR.

> I'd like this code to sit inside QuantityCollection if possible, since we will use it for Debrief persistence (which won't be using XSTream).

I think that we have to adapt it to Debrief persistence, in any case.
Another way (within ObjectCollection) is that we design Measure values (the field values in ObjectCollection) as one unit object and list of numbers. It would be enhance performance (collection object will occupy less memory and all operations will be faster). I'm not sure if it is possible. In this way we don't need XStream converter (now converter converts values to one unit + list numerics).

> Oh, and could we also reduce the storage space of TemporalCollections, by storing XML Dates instead of the current objects?

I'm not sure what objects you mean. The times object is saved as simple long.

PS
I have also added several aliases for geotools classes, It will reduce size (minimal).

**Comment by IanMayo** [comment]
Hi there,  that all sounds fine.  I look forward to testing /playing,  when I'm back at work on Tuesday. 
One comment - the time improvement would be to use human readable XML standard rate format,  rather than computer readable long values (to allow some manual text fiddling).

**Comment by pecko** [comment]
> Hi there, that all sounds fine. I look forward to testing /playing, when I'm back at work on Tuesday. 

OK.

> One comment - the time improvement would be to use human readable XML standard rate format, rather than computer readable long values (to allow some manual text fiddling). 

OK. I will use similar trick (marker class) as I have already used for measures. 

Will I try to convert ponits to simple lat/lon xml?

**Comment by pecko** [comment]
> One comment - the time improvement would be to use human readable XML standard rate format, 

Added as a new commit to the issue129 branch.

**Comment by IanMayo** [comment]
Yes please,  points as simple XML. 

Could you create a PR?   That's easier to track progress.

**Comment by pecko** [comment]
> Yes please, points as simple XML. 

Will do it tomorrow.

> Could you create a PR? That's easier to track progress. 

I have created https://github.com/debrief/limpet/pull/195.

**Comment by pecko** [comment]
I have updated the PR. Added Point converter and marker classes comment.

**Comment by pecko** [comment]
I have tested usa.csv from american cup. Now, the xml is cca 500k, was 1800k.

**Comment by pecko** [comment]
BTW The persistence with Point isn't backward compatible. You have to create a new *.lap to test.
It is possible to create it so it be backward compatible, but, IMO, it will unnecessarily create more complex code. 
Please let me know if you want that it be backward compatible, that is, that a lap file created with old version of limpet be imported (opened in the editor) properly.

**Comment by IanMayo** [comment]
No, we don't need backwards compatibility.
