### ISSUE TITLE
Drag/drop CSV into data manager

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#14]
We're going to need this pretty early.  We're also going to need it in both Debrief and Limpet standalone.

As much functionality as possible should go into "Core", with a minimum amount in "RCP".

The import will need this functionality:
- determine if the first column is time data. If it is, then all the datasets will be Temporal
- determine if the first row is headings. If it is, use these to name the series.  If not, name the series as _time1_ (if applicable), then _value1_, _value2_, _string1_, _string2_, etc. (as applicable)
- if the first row is headings, check each heading for a value in parentheses afterwards - try to use this as units, like:  **Vehicle Length(m)** - we can used this to create a dataset titled **Vehicle** that has units in **metres**.

**Comment by IanMayo** [comment]
You've got this one next, please Peco.

I'll draw up some requirements.

**Comment by pecko** [comment]
@IanMayo 
Please, provide a few sample csv files if it's possible?

**Comment by IanMayo** [comment]
Sure. Building requirements document here:
https://docs.google.com/document/d/1IKZmZITSPZx8qD8eR1K_JsTHL95HtKJnmAnXHvFye7I/pub

**Comment by pecko** [comment]
I have started some work in the issue14 branch: https://github.com/pecko/limpet/tree/issue14

**Comment by IanMayo** [comment]
looks fine so far. 

I may need to step in once you've done a bit more CSV processing

**Comment by pecko** [comment]
@IanMayo 

I wanted to see look at code and maybe advice something. For instance, you maybe prefer another library.

I just need the code explore slightly in order to understand how to convert csv to list of collections.
Maybe you can help me with just some concepts. For instance,
- column in csv is a collection (???)
- name is determined as you described; values are column values
- an example non-temporal and temporal classes
- all collections (columns) are added to store

....

**Comment by IanMayo** [comment]
1. "Column in CSV is a collection".

If the data starts with a time column, then we're going to produce a TemporalQuanityCollections for each of the of the following columns. (Since temporal... consists of pairs of a time plus a value).

If the data doesn't start with a time column, then we're going to produce a QuantityColumn for each column in the CSV file.
1. "Name is determined as you described".  The name comes from the String in the first row.  Or use a counter "Column 1", "Column 2" etc if there isn't a String in the first row.
2.  The linked document includes some sample data.
3.  Yes, all columns are added to the store.

**Comment by pecko** [comment]
I hope that I understand. Will try to solve it during day.

**Comment by pecko** [comment]
@IanMayo 

I have implemented a few features.
Now you can drop example 2 and example 3 (https://github.com/pecko/limpet/blob/issue14/info.limpet.sample_data/data/intervals.csv or https://github.com/pecko/limpet/blob/issue14/info.limpet.sample_data/data/frequences.csv)

It isn't too robust yet. but you can review and advice.
