### ISSUE TITLE
Add code coverage reporting

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#158]
I'd like to aim for a high proportion of code coverage in Limpet. 

To support this, we need test code coverage reporting.

Could you investigate a code coverage library to use, hopefully one that integrates nicely with Travis, Java and Maven.

**Comment by pecko** [comment]
I have created the PR: https://github.com/debrief/limpet/pull/161

The PR uses jacoco: http://eclemma.org/jacoco/

You can test it by building project and opening LIMPET_HOME/target/jacoco/report/index.html in your browser.
After applying the PR, coverage report should be uploaded to limpet-release's gh-pages and accessible by http://debrief.github.io/limpet-update/coverage/report

BTW
Currently total coverage is about 30% (includes the info.limpet, info.limpet.rcp and info.limpet.test plugins). Maybe, we should remove the test plugin, but it is 99% covered .
Mostly uncovered stuff is UI.

**Comment by pecko** [comment]
A screenshot:

![coverage](https://cloud.githubusercontent.com/assets/534584/11614704/805ce4e8-9c4a-11e5-979c-7e4b871f9c9d.png)

**Comment by pecko** [comment]
I have rebased the PR to use a new token.

**Comment by pecko** [comment]
BTW maven cache works fine.

**Comment by pecko** [comment]
It works, but seems miss some styling. 
Checking...
See http://debrief.github.io/limpet-update/coverage/report

**Comment by pecko** [comment]
The resource starting with dot don't shown on github's gh-pages by default.
It is solved by https://github.com/debrief/limpet/commit/c64cc14b8edbdaa5836f3f67ae136d30981ca412

Now, http://debrief.github.io/limpet-update/coverage/report looks correctly.

**Comment by IanMayo** [comment]
Great - I love it.  Well done!

Now we just have to get improve the green vs red proportions...

**Comment by IanMayo** [comment]
Hmm, we can drill down to view the source for code in the info.limpet project, but not in the info.limpet.rcp project.

So, from this page, it isn't possible to view the code:
http://debrief.github.io/limpet-update/coverage/report/info.limpet.rcp.xy_plot/XyPlotView.html

But, it is possible from here:
http://debrief.github.io/limpet-update/coverage/report/info.limpet.data.store/InMemoryStore$StoreGroup.html

Any idea why this isn't working?

# 

Fixed!

https://github.com/debrief/limpet/commit/394e3c48276610fb835c972937017c8c5bd1f81e

**Comment by IanMayo** [comment]
Ok, I'm happy that this is now working.

**Comment by pecko** [comment]
> Ok, I'm happy that this is now working.

Great.

> Now we just have to get improve the green vs red proportions...

There is the EclEmma product (http://eclemma.org/).It is Eclipse plugin which shows test coverage directly in Eclipse. It is great when you want increase coverage. You don't have to build after each changes; just start test and look at results in Eclipse view.
