### ISSUE TITLE
Include HTML content in gh-pages branch

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#168]
The release process has worked fine.

But, the release process "wipes" the gh-pages branch. This causes a problem since I'd like to put some HTML content in the gh-pages branch - just in case a user tries to browse to the p2 URL instead of entering it into the updates target.

Can you try to think of a process where I can safely provide some HTML content in the gh-pages that doesn't get wiped in a release.

Here's the options I can think of:
- I include the content in the limpet-releases master branch. You do a "git archive" of this into your empty folder before unzipping the build app into it.  Then the whole folder gets committed back to gh-pages
- _hmm, can't think of any others_

Any suggestions?

**Comment by pecko** [comment]
Yes, it is doable. We can clone the gh-pages branch, remove unnecessary/old stuff and add only what we want.
Will you create a index.html or I will do it based on Eclipse update sites, for instance?
We should probably keep some older update sites (1.0, for instance when creating 1.1 or something similar)

**Comment by IanMayo** [comment]
1. Yes, I'll create an index.html (again :-)  ), and include it in the gh-pages branch.
2. I'm unclear about how the versions work.  We have a folder called 1,0.  In it we could have version 1.0.0 and 1.0.1 of each plugin.  What is the role of the 1.0 top level site?

**Comment by pecko** [comment]
1. OK
2. We should keep older update site (at least main versions 1.0, 1.1, 1.2, 2.0 ...) because some users will want to use older sites.
   We will keep just latest main version. We will remove 1.0.0 when adding 1.0.1.
   Other solution, we can just keep the latest version if you want.

Also, will we update release/distribution here too?

**Comment by IanMayo** [comment]
1. Let's keep older versions.
2.  Hmm, I quite like using the GitHub releases process/page.  Maybe we should change the name of the limpet-release project to limpet-update.  Then it's clear that limpet itself comes from the limpet repo, and only updates from limpet-update.  

What do you think?

**Comment by pecko** [comment]
Agree. Please keep my write permission in order to easier test.
I will probably have to create version 1.0.2. Will test locally firstly.

**Comment by IanMayo** [comment]
Sure,  ok.   

Note : eclipse update didn't work due me on  1.0.1

**Comment by pecko** [comment]
> Note : eclipse update didn't work due me on 1.0.1

I have seen that. Will review today later (firstly locally). I suppose that version 1.0.0 isn't defined correctly and will probably have to create version 1.0.2, but will test firstly locally.
I will start a little later, but you can rename update site and create index.html.

**Comment by pecko** [comment]
The PR: https://github.com/debrief/limpet/pull/189

I have created the page based on http://debrief.github.io/limpet/
It will be shown at http://debrief.github.io/limpet-update/1.0

Screenshot:
![limpetup](https://cloud.githubusercontent.com/assets/534584/11867573/3eadaa26-a4b2-11e5-8dc3-762f6e772142.png)

**Comment by IanMayo** [comment]
Don't you mean limpet-update?

**Comment by pecko** [comment]
Yes, http://debrief.github.io/limpet-update/1.0. It works fine.
