### ISSUE TITLE
Create sample project

### ISSUE THREAD

**Issue by pecko** [debrief/limpet#175]
We should create an action to create a sample project (SampleData by default) which would include contents from the info.limpet.sample_data plugin.

**Comment by pecko** [comment]
I will convert the info.limpet.sample_data project to a plugin and add them to info.limpet.rcp.feature. I hope it is OK.

**Comment by IanMayo** [comment]
The PR doesn't seem to include the sample data.  Or, does it have to be run from outside the IDE in order for this to happen?

**Comment by pecko** [comment]
The sample_data project has already existed in the repository. The PR just convert it to Eclipse plugin. The plugin will be included in IDE (the info.limpet.rcp.feature feature).

**Comment by IanMayo** [comment]
Sorry, I explained that wrong.  When I run the wizard, it doesn't pull in the sample data.  But, I guess I need to run it outside the IDE.

**Comment by pecko** [comment]
You should add the sample_data plugin in PDE Runtime. It should be work from Eclipse as well as standalone RCP application.

**Comment by pecko** [comment]
If it doesn't work when you include plugin, it is a bug.

**Comment by IanMayo** [comment]
Ok. It worked for me in an exported Limpet, not from the IDE. But, that isn't a problem.

Will modify the PR to tidy some dialog wording.

**Comment by pecko** [comment]
OK. I will check for your modifications.

**Comment by pecko** [comment]
> It worked for me in an exported Limpet, not from the IDE.

It should be work. Do you sure include the sample_data to Launch Configuration?
Anyway, I will check double.

**Comment by IanMayo** [comment]
Working fine for an built/exported version.

Will ignore problem for running from IDE until it becomes a problem.
