### ISSUE TITLE
Initial export operations

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#18]
We need to prove/learn about exporting data.

Suggest we provide these export operations:
- export to clipboard as CSV (one or more collections)
- export to CSV file

**Comment by pecko** [comment]
Maybe could start, but would be good apply the PR for #12 first.

**Comment by pecko** [comment]
I have created bas code for this feature: The PR: https://github.com/debrief/limpet/pull/213

Included:
- exporting some ICollection (TestExport tests all collections created by SampleData..getData(20))
- "copy to clipboard" and "copy to file" action; for now, they are added only to context menu

Notice:
For now, the actions are shown only when selecting ONE ICollection.
I'm not sure how to export multiple collections. I suppose that you want export them to one file (similar to usa.csv). However, it means that we have check that actions has the same size and, for temporal collections, probably, same times. 
@IanMayo  Please review and advice.

**Comment by IanMayo** [comment]
Your thoughts on "multiple collections" are quite right.

We'll hand them in a separate issue.
