### ISSUE TITLE
Create RCP Application for standalone Limpet

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#19]
As previously discussed, we wish to provide Limpet as a standalone application (in addition to Debrief).

We have the Limpet.RCP project.  I guess we'll may need new projects in order to define the application and the product.

I expect we need to define both an Application and a Product.

**Comment by pecko** [comment]
I will create separate application and product ext. point so we can easier control actions/perspective.

**Comment by pecko** [comment]
I have created first prototype. 

![image](https://cloud.githubusercontent.com/assets/534584/10120641/675735c2-64c6-11e5-9af0-5e6520076ad6.png)

**Comment by pecko** [comment]
The PR: https://github.com/debrief/limpet/pull/51

The PR also fixes #42

**Comment by pecko** [comment]
I have merged. There is a issue related to the About dialog, but I will open a separate bug and you can test (and maybe open more bugs).
Mostly icons have to be changed.

**Comment by pecko** [comment]
Fixed

**Comment by IanMayo** [comment]
@pecko - the new info.limpet.rcp.product sources have lots of compiler warnings.  

I'm aiming for "zero warnings" as a way of maintaining code quality.

It would be acceptable for you to suppress the warnings.  But, could you have a look/think at the code and check that there aren't tidier code-related solutions?

**Comment by pecko** [comment]
@IanMayo 
I suppose you mean the info.limpet.rcp plugin.
I have tweaked main rcp classes (application, action bar, advisor, window advisor) from Eclipse IDE and they have a lot compile warnings (mostly using non-API and some pre jdk7 code):

We have two solutions:
- create own classes mostly from scratch (more correct solution, but would takes more times and introduce more bugs probably; not sure that it is better)
- fix warnings as possible and add SuppresWarnings for remaining (faster and probably more reliable)

Question: we fixes all compiler errors/warnings that we get with standard Eclipse JDK7 compiler. Right?

Notice:
I think that it is better if you can open a new issue for this and other rcp issues (I already open #52)
-

**Comment by IanMayo** [comment]
Sure, that's all fine.  The second solution is acceptable. 

Will create issue.
