### ISSUE TITLE
Porting with Octave (Matlab)

### ISSUE THREAD

**Issue by nikilp** [debrief/limpet#2]
Matlab has a solid community of users performing numerical calculations. It has open-source alternative - Octave (https://www.gnu.org/software/octave/). Octave has this http://sourceforge.net/projects/octclipse/ development environment built upon Eclipse's Dynamic Languages Toolkit. This should make it easy to port solutions and algorithms already programmed for Matlab/Octave to Limpet.

**Comment by IanMayo** [comment]
Demote.
