### ISSUE TITLE
More build process

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#205]
@pecko - I've just tagged a release, and noticed we don't currently deploy the builds to releases (like we do with Debrief).

Would you mind changing the Travis build so that we can deploy the multi-OS builds to the Releases for tagged builds?

Aah, does our Maven build also include the command to update POM versions, like we can with Debrief?

**Comment by pecko** [comment]
> Aah, does our Maven build also include the command to update POM versions, like we can with Debrief?

If you mean on the feature described in debrief wiki: https://github.com/debrief/debrief/wiki/Getting-started-in-Debrief-development, 

> Note: When you update version of some plugin you also have to update version in pom.xml or call (before committing):
> 
> mvn org.eclipse.tycho:tycho-versions-plugin:update-pom

then yes. It is tycho plugin feature and can be used in any tycho build.

**Comment by pecko** [comment]
I have created the PR: https://github.com/debrief/limpet/pull/208

I have to merge it in order to test.

**Comment by pecko** [comment]
@IanMayo 

I have merged the PR, but we should create a tagged commit in order to deploy release. Could you please test it?
It is possible that I haven't set oauth token correctly (I have used one that you send me before)

Notice: I haven't rename distribution archive. Please let me know if I should do it.

**Comment by pecko** [comment]
Added the 20151223b_1_0_4 tag to test releases.

**Comment by pecko** [comment]
@IanMayo 

Now, it works, but I have used 'travis setup releases' and my username and password. You probably want to change to use your credentials.

Link: https://github.com/debrief/limpet/releases

**Comment by IanMayo** [comment]
Hopefully I've switched to the correct Travis releases token

**Comment by IanMayo** [comment]
Nope, it currently looks like I've got it wrong, grrrr:
https://travis-ci.org/debrief/limpet/builds/98546811

**Comment by pecko** [comment]
It's weird. It looks that deploy_ghpages.sh returns an errors.
Could you (or me) revert the latest commit?

**Comment by IanMayo** [comment]
sure, please revert it.

**Comment by pecko** [comment]
Reverted, but previous build (handle the range constant being deleted) also failed.

**Comment by IanMayo** [comment]
can you carry on looking into it?

**Comment by pecko** [comment]
checking...

**Comment by pecko** [comment]
Could you maybe change api key?

**Comment by IanMayo** [comment]
sent via email

**Comment by IanMayo** [comment]
All seems to be working now :-D

**Comment by pecko** [comment]
We probably can close this issue.
