### ISSUE TITLE
Introduce smoothing operation

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#21]
Smoothing operations are a common requirement for real world data.

The smoothing could be either via a moving average or fitting a curve (regression).

But, significantly, both of these examples are tuneable.

So, this operation will have at least one editable value (such as the window size for the moving average).

Users should be able to select the operation (possibly from the Algorithm Audit view), view the properties in the Properties View, and change the editable value from there - seeing live updates in the down-stream dataset.

I suggest we use a windowed moving average.  The window size would be the configurable attribute.

**Comment by IanMayo** [comment]
@dinko, could you try this one next?

It will be useful in testing/proving the dynamic data updates.

I propose the API expects that there's just a single collection in the "selection", and that this collection is a quantity collection.

Happy to help out as necessary.

**Comment by dinko** [comment]
I think you meant @dinkoivanov ;)

**Comment by IanMayo** [comment]
Duh, sorry @dinko
