### ISSUE TITLE
Refactor DataManagerEditor actions to standalone classes

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#217]
The DataManagerEditor class defines some actions (create objects, add layer, export to CSV).

It would be more tidy if these actions were declared as standalone classes.  This would allow us to organise the actions from the plugin.xml, and it would also help with testing.

Where UI support is required, the relevant support functions should be added to the IContext object.

**Comment by pecko** [comment]
@IanMayo 
Could you please review/apply several PRs that I created?

**Comment by pecko** [comment]
> This would allow us to organise the actions from the plugin.xml,

If you mean that we use declarative actions (via the menus extension point), then we should skip/close the PR https://github.com/debrief/limpet/pull/214

**Comment by IanMayo** [comment]
ok, will close #214

**Comment by IanMayo** [comment]
thanks for making a start.  But, I had a different plan for the XML declarations.

This issue just covers moving the blocks of inline code into separate classes - to clean up the Data Manager class, and so that they can covered by test coverage.

For the XML definitions I **think** I want to create a new LimpetOperation extension point, with:
- a text block describing the background to the operation
- a series of child elements to handle the _appliesTo()_ logic. Optionally these child elements can include messages explaining why the appliesTo() test failed.
- some category information, to allow grouping/filtering of operations

Once we have the appliesTo() logic declared in XML elements, we can perform the _appliesTo()_ logic without actually loading the class.  A set of standard responses can indicate why the current selection isn't suitable for that operation (in the future Operations Browser view).

We will create a class that goes through the plugins, and loads all LimpetOperations.  It's this class that will provide the actions in the popup menu.

So, could you please change your PR so that we've just refactored the DataManagerEditor code, and remove the XML Command definitions.

**Comment by IanMayo** [comment]
Aah, @pecko  - here is my plan for declaring operations via XML:  https://github.com/debrief/limpet/issues/65

**Comment by pecko** [comment]
I have created the PR: https://github.com/debrief/limpet/pull/221.
Since we will use our separate extension point to contribute actions, I have comment registering the editor context menu (commit: https://github.com/debrief/limpet/commit/fc38eb4b58d798dac237605a35a4c2e2fec08338). It removes unnecessary Eclipse actions.

**Comment by pecko** [comment]
I have removed the org.eclipse.jface (and org.eclipse.swt) dependency from the info.limpet plugin. Commit: https://github.com/debrief/limpet/commit/755461fa2fb64fafe49d3cfbe66ae224884c9915

@IanMayo 

Please review. I have use only changed AbstractLimpetAction.

**Comment by IanMayo** [comment]
Fixed in #221
