### ISSUE TITLE
Simple Limpet persistence

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#22]
We wish to be able to store the contents of the Data Manager to XML.

I propose that we use XStream for this, potentially backed up by XSD schema validation (to ensure we have a maintained XML schema).

The contents of the Data Manager is expected to be an IStore object - though the IStore object requires further implementation work.  

To start with, let's have a "dumb" XStream export, without any configuration.

This issue will be easier when we have the Data Manager as an editor #38 

We should defer this issue until after we've re-organised how data is stored ( #41 )

**Comment by IanMayo** [comment]
@pecko  - could you make this your next issue?

Our data model will probably continue to change, but this will let us learn about persistence issues.

**Comment by pecko** [comment]
You want to do using XStream (similar as Debrief). Right?

**Comment by IanMayo** [comment]
Yes, please

**Comment by IanMayo** [comment]
Peco - I think this is the next issue, please.

**Comment by pecko** [comment]
OK.

**Comment by pecko** [comment]
Question/Advice:

I have reviewed a little how it works in Debrief. We have a few solutions:

1) reuse some Debrief code (mostly from org.mwc.cmap.legacy)

We could treat the org.mwc.cmap.legacy plugin as common plugin for both (limpet and Debrief)
Requirements: build it separately and create p2 update site similar to https://github.com/debrief/debrief/issues/1352
We will have 2 (or 3) update sites: common (mostly debrief legacy plugins), limpet and maybe debrief

2) use WTP XML stuff (requires creating EMF model and it is hard to change xml schema)
3) start from scratch using Debrief model as starting point 

Maybe faster than 1), but we will have probably a lot duplicate (or similar) code.

WDYT?

**Comment by IanMayo** [comment]
This solution is just for Limpet. 

We'll handle Debrief separately.

So, simply dumping the InMemoryStore to XML via Xstream will be fine.

**Comment by pecko** [comment]
OK. 
... and loading (reading) it, of course.

**Comment by IanMayo** [comment]
yes :smiley:

**Comment by pecko** [comment]
I have started on this issue in the issue22 branch.
The saving/loading in test (TestPersistence.java) works fine, but in editor it create a very big (250MB) file for small store. 
I have added store with 2 items; try to remove all collections beside one, but the file is always very big, invalid and contains a lot Eclipse classes.

@IanMayo 
I will continue on this issue tomorrow, but you maybe can look at the branch and let me some advice. You probably know xstream better than me.

**Comment by IanMayo** [comment]
Hmm, maybe there's something cyclic.  But, xstream should reference existing objects by id.

Will have a look tomorrow

**Comment by pecko** [comment]
It is Eclipse listener. I will fix that.

**Comment by pecko** [comment]
Now the following operations works:
- create a *.lap file and it will be open with Data Manager editor
- generate some data with your actions
- save it
- close and reopen

It is still roughly, but base operations work.

@IanMayo Please review a little the issue 22 branch and propose future actions.

**Comment by IanMayo** [comment]
I've got a compiler error, related to build:
![eclipsewarnings](https://cloud.githubusercontent.com/assets/1108513/10333159/04f91f78-6cda-11e5-8d6d-76cf750bd05d.png)

**Comment by IanMayo** [comment]
Switched xstream mode (for how it refers to internal objects), so it doesn't use XPath, it just creates an id for each entity created:
http://x-stream.github.io/graphs.html#ids

No cyclic memory troubles!

Can't change your branch, so will push my own.

**Comment by pecko** [comment]
It looks OK. I suppose that you fix above mentioned compile error.
I think that we could apply the PR https://github.com/debrief/limpet/pull/116 and continue enhance editor with new issues.

**Comment by IanMayo** [comment]
Done
