### ISSUE TITLE
Trouble on Windows install with **space** in parent folder

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#225]
A user ( @russcrowley ) has installed Limpet (using the _Getting started with Limpet_ guidance). He encountered this error:

![capture](https://cloud.githubusercontent.com/assets/1108513/12112625/aa054012-b395-11e5-9811-bbb64d5bc788.PNG)

The error indicates a problem with the 40th character. It looks like the 40th character is a space.  Clearly we need to allow spaces in the path.

@pecko - could you investigate this?  (low priority)

**Comment by pecko** [comment]
Spaces in the path work fine on Linux. Will review on Windows.

**Comment by pecko** [comment]
It works fine on Windows 7, too.

@IanMayo 
Could you attach a log file?

**Comment by IanMayo** [comment]
@russcrowley  - would you mind trying to see if you can reproduce this problem?

**Comment by russcrowley-zz** [comment]
Just tried it in 'Limpet Original' folder and it worked fine. Thanks.

**Comment by IanMayo** [comment]
Ok, resolved.
