### ISSUE TITLE
Refactor limpet RCP projects

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#235]
@pecko has suggested that we refactor limpet RCP into product-related and non product-related plugins.

This is a good idea.

So, please refactor **info.limpet.rcp** into **info.limpet.rcp.product** and **info.limpet.rcp**

Hmm, so far - the only features that I can see should stay in **product** are the DataManagerEditor & supporting classes.   But, there's a chance that I'd like to distribute this editor as part of Debrief in the future.

Maybe it's not necessary.  Thoughts peco?

**Comment by pecko** [comment]
I thought that we separate the Limpet product/rcp part (the application, product, intro extension points and associated classes). This is specific Limpet RCP part which certainly will not be required with Debrief.

All other Limpet UI (editor, views, associated commands, classes...) should be in separate plugin and will be available for Debrief and other application. Debrief users can, but don't have to use that. 

You already plan to use Limpet analysis views based on https://github.com/debrief/debrief/issues/1417: 

> 5 Limpet analysis views will work when an entry is selected from the Measurements folder

**Comment by IanMayo** [comment]
Sure, I know I'll use Limpet views in Debrief.  It looked like I may ultimately use almost all Limpet RCP code in Debrief - so then wasn't sure what I would refactor out.

**Comment by pecko** [comment]
We certainly doesn't need pure RCP Limpet part (Debrief has its RCP stuff) as the product, application, intro, perspective. That is: the info.limpet.rcp.product package and mentioned extension points. It is small part, but it is only required for Limpet. It is just suggestion and usual Eclipse praxis.

Maybe we misunderstanding term: Only Limpet specific part is Limpet RCP (application, product, intro).  My suggestion that call it info.limpet.rcp or info.limpet.rcp.product.
Other Limpet code in info.limpet.rcp is ordinal UI that will be common for Limpet and Debrief. It can be used as ordinal plugin in standard Eclipse, for instance. Suggested name: info.limpet.ui

More important is that we add qualifier, so, Debrief (or other stuff) always has the latest Limpet changes available. I could do both of that within this jira.

**Comment by IanMayo** [comment]
Yes please - do it :-)

**Comment by pecko** [comment]
I have created PR https://github.com/debrief/limpet/pull/240.
@IanMayo Please review the PR comment.

**Comment by pecko** [comment]
@IanMayo 

Could you please comment the following (from #240):

>  Also the info.limpet.ui plugin still contains the info.limpet.rcp\* packages. We should probably refactor them to org.eclipse.ui*.

**Comment by IanMayo** [comment]
Yes, I noticed that. Please rename them.

**Comment by pecko** [comment]
starting...

**Comment by pecko** [comment]
The PR: https://github.com/debrief/limpet/pull/242

If you face an exception when starting Limpet first time in old workspace, you should:
- reopen all opened editors
- reset perspective

@IanMayo 

This PR can affect your Debrief-Limpet integration branch. You should rename info.limpet.rcp packages, Limpet view ids and editor id.

**Comment by pecko** [comment]
@IanMayo 
I think that this issue can be closed.
