### ISSUE TITLE
Overcome Geospatial clash

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#236]
When I included Limpet in Debrief, I had a large (partially expected) problem with the spatial libraries.  Debrief and Limpet are both trying to integrate GeoTools libraries.

It is probably possible to overcome this through fancy build/architecture instructions, but I have a tidier solution.

I'd like Limpet to use Dependency Injection to support two different geo libraries.  Core limpet will use a low fidelity (hand crafted) library to do spatial calculations.   Limpet in Debrief will use GeoTools to perform spatial calculations.

So, to support this, we'll do the following:
1. change the Limpet storage collections to store 2d Point objects
2. allow the Limpet Core plugin to receive, (and make accessible) the Geospatial implementation.
3. Let the Limpet product explicitly set the low-res library in Limpet Core
4. Let the new Debrief Limpet Integration plugin set the GeoTools library in Limpet Core

The spatial calculations will receive 2D point objects, and call the GeoCalculator to perform calcs.  Only the Debrief implementation will actually be using GeoTools (with it's understanding of earth models & projections).

Letting the Limpet application just support low-res provides an "upgrade path" to Debrief.  In the future, should Limpet users justify inclusion of hi-res spatial calculations, the Debrief Limpet Integration solution can be "ported" to Limpet.

I hope to start work on this today, but will expect to pass the task to @pecko later on.

Any feedback/suggestions, @pecko  or @dinkoivanov ?

**Comment by pecko** [comment]
@IanMayo 

I don't sure how you try it, but we also have to set Limpet to tycho target platform. We have two solutions:

1) separate common foreign libraries to separate git repository that will be used by both Limpet and Debrief
or
2) separate Limpet's foreign libs/plug in separate feature that will not be used by Debrief since Debrief has its libs/plugins

Solution 2) will enable us to implement your request described above.
I can do it within #235 too.
For your testing you can just import both repositories in workspace, but don't import Limpet's geotools. Limpet-Debrief integration will use Debrief's geotools in any case. Maybe we will have to fix/adapt something, but, IMO, it should be work.

I will start today later and you can push your stuff in some branch and describe me if there is any issues.

**Comment by IanMayo** [comment]
I know, I had been thinking how good 1) sounded.  Then a download of the Debrief repo would "just work" - though it would lack Limpet capabilities.

But, I think that 2) is the solution that's easier to understand & maintain.

Will update you later.

**Comment by IanMayo** [comment]
Duh, I can't just remove GeoTools from Limpet.  Core Limpet uses it for the Units of Measurement code.

**Comment by pecko** [comment]
Right, solution 2) is easier and enable to fulfill your requirements. I suggest it, for now.

The solution 1) has advantage that we would have/maintain foreign libs/plugins on one place. (Debrief, Limpet or some other application). It is similar how Eclipse Orbit works. But, it is for later (also not too hard to implement it).

**Comment by IanMayo** [comment]
Ok. I made a start, but got stuck straight away (since Limpet requires UoM).  In my "integration" workspace, I also tried closing the **info.limpet.geotools** project.  But, that just introduced the failed dependency on that project.

I'll do some small steps (to refactor out the GeoSpatial calculator), but then will have to pass the problem to you - for you to carry on with.

**Comment by pecko** [comment]
> Duh, I can't just remove GeoTools from Limpet. Core Limpet uses it for the Units of Measurement code.

You should be able to use it from Debreif, beside we name it differently. If so, we should use the same name for common plugins.

**Comment by pecko** [comment]
OK. We have to use the same name (org.geotools or similar) for geotools and other plugins that could be common (maybe JFreeChart and so).
For testing, you can just rename Limpet's dependencies in your workspace to require Debrief's geotools (I suppose info.limpet's MANIFEST.MF) and delete info.limpet.geotools from workspace.

**Comment by pecko** [comment]
@IanMayo 
I think that this issue can be closed.
