### ISSUE TITLE
Consideration of technology for Stacked Charts Edit Mode

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#258]
I've just been doing some research into candidate technologies for the editor-mode of our new Stacked Charts View.
## BIRT

The BIRT report designer is really capable, I watched a video of a chap connecting to a SQL data source & generating a custom report.  But, BIRT is too low level for my users.  They don't have to go out & find the data source - the data is already present in the application.  Plus, they don't need to any aggregation/filtering/sorting on the data.  We require a small subset of BIRT functionality, and we only need charts to be produced - not tables.

So, BIRT doesn't seem right for us.
## GEF

I also watched a GEF4 presentation. GEF4 is great for a graphical editor - where a user starts with a blank canvas and drops in entities from a palette.  We're not in this scenario.  Well, we do have some entities:  chart, axis, title.  But they aren't dropped anywhere on a form, they're within a tightly defined information architecture.

So, GEF graphical editing seems beyond what we require.
## EMF

I've had an interest in EMF over the years, but never had the requirement to learn it.  I see it's value in the enterprise, with complex teams of people working on diverse technologies.  But, unless it brings benefits I'm unaware of, "code generation" is a level of complexity too far for our current Travis CI process.
## Draw2D

I finally got to Draw2D, with its lines, shapes, layout managers.  This  looks close.  I can quite clearly see how we could render a ChartModel - generating Draw2D widgets for charts, axes, datasets, etc.  

Once arranged within resizable Eclipse layout managers (Border & Grid) the editor view would resize to suit the RCP View resize.

**Comment by dinkoivanov** [comment]
**Regardging GEF/Draw2D**
You can view GEF as an MVC layer on top of Draw2D. Like what JFace is to SWT. You can implement a tree in SWT, but you would more likely use a JFace TreeViewer.
In GEF you don't have to have a palette to drop elements from, while you might still want to have DnD functionality. Besides the freeform layout, GEF(Draw2D) supports any other kind of layout where items are arranged in a various well-defined ways. 
I agree that it goes beyond what we require and we can also implement "edit" mode using the lower level Draw2D as well. However in such case we'll have to implement some features like:
1. Chart/Axis selection handling and highlighting (Draw2D does not have a concept of selected shape).
2. GEF provides strict protocol how/when/which "view" shall be updated when "model" changes. With Draw2D, we'll need to handle that. For example when axis scale is changed, we'll need to find and update the corresponding visual element and possibly re-layout the parent.
3. Undo/Redo - GEF provides a command stack integrated with Eclipse infrastructure (undo/redo actions).
4. Drag and Drop - GEF handles that on a more abstract level (source - target) than Draw2D (listeners)

**Regarding EMF**
Code generation is usually only done during designtime, it is the user who generates the code, after EMF metamodel change. It does not need to affect the CI process in any way. I would say those are the benefits for me:
1. Event notification API - well structured and hierrarchical
2. XML (XMI) persistence
3. Additional reflection (generic) API
4. Code generation / diagram editors / good tooling support in general.

**Another option**
In the end we can simply edit the chart metadata using form-based (SWT) editor with regular text fields, drop-down lists and buttons. The user will again manipulate a "not-so-visually-expresive" chart abstraction. That's simplest I think and the cheapest option to implement the editor. And if user can quickly switch to "view" mode, then I guess it's OK.

**Comment by IanMayo** [comment]
Thanks for that, it's a real insight.  It mostly makes sense, though some elements don't seem that significant:

GEF.1: Selection.  I imagine our significant entities (axis, chart) would be declared as SWT Controls/Composites - then we can lay them out, select them, drag them, etc.  The control itself would consist of Draw2D lines/shapes.
GEF.2: Updates.   Our UI model seems really simple, so there would be little cost in regenerating the whole editor view on change.  I guess the GEFs strict update sequences require coding/configuration - which could represent a cost.
GEF.4: Drag/Drop.  In my current mockup, it's SWT Control items that get dragged/dropped/:  an axis can have a list of datasets, but it's the items in the list that get dragged.  Or, to drag a chart/axis to change the sequence we could add a "handle" control that gets selected & dragged.

EMF: user generates code:  aah, in that case I appreciate that it's not a build problem, cool.

Ok @dinkoivanov  - let's see if Sambi jumps in with anything in the next 24 hours.

Unless we've missed anything, I'm happy for us (you) to set off down the GEF/EMF route - partially as a learning exercise for me..  But, I'll be nervous of a "complexity explosion" happening - so lets keep things as small & simple as possible :-D

**Comment by dinkoivanov** [comment]
Just to record another idea:
BIRT is made of lot components (runtime, designtime, etc). We can for example reuse only the Chart API from BIRT (it's EMF based). Consider the packages **org.eclipse.birt.chart.model.**\* packages here:
http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.birt.chart.doc.isv%2Fchart%2Fapi%2Findex.html
That might be too much I guess, but perhaps we can use it as a reference.

**Comment by sambireddyt** [comment]
As per the doc, this editor is more like chart view designer. I think, in this case, GEF is perfect fit.  As Dinko mentioned, all low level stuff are abstracted or hidden and we just get to work with chart edit parts with GEF.

![editor](https://cloud.githubusercontent.com/assets/1883173/14972394/62ea235c-10a9-11e6-93fa-11362a0c6517.png)

And also, we should be able to provide preview as and when chart state changes.

I am a bit confused with chart axis selection!  are we going to use any chart rendering library or we will build our own?  If we are going to use libraries like swt charts, we may have to do some tweak them  to render them as shapes.

**Comment by dinkoivanov** [comment]
I imagine that in "view" mode, the chart is rendered using library like JFreeCharts, while in edit mode it is rendered with GEF/Draw2D. This rendering would be an approximation, not precise WYSIWYG experience.

**Comment by IanMayo** [comment]
Yes, @dinkoivanov - the edit mode will just be an abstract version of the chart.  But, I have recently recognised the merits of a _live preview_. Maybe this could go in the centre of the **Chart** UI element in the above screenshot.

Original diagram updated:
![withlivepreview](https://cloud.githubusercontent.com/assets/1108513/15008912/5abf3248-11db-11e6-8ea1-b13083fed253.png)

**Comment by IanMayo** [comment]
Ok, GEF is working well for us.  Case closed - thanks @dinkoivanov
