### ISSUE TITLE
Initial architecture for stacked charts

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#262]
@theanuradha - once you're on top of the issues you're currently working on in the Debrief repo, 
I'd like to get you started here in Limpet please.

You'll be creating the initial skeleton for the Stacked Charts:
https://docs.google.com/document/d/1_IR773qKa9m4ZblFYd-m4WSW65yxym0UEtrBPIrUDL4/edit

We'll be using this RCP View in Debrief.  But, Debrief's data-analysis capabilities are being created here in the Limpet repository, before being "pulled" over to Debrief.

This issue is to create the "two-sided" RCP View. It will have a single JFreeChart on one side, and a "mock" RCP form on the other that contains, for example, three push buttons.   The view menu will have a single "Edit" button, that switches between the two modes, as described here:
https://docs.google.com/document/d/1_IR773qKa9m4ZblFYd-m4WSW65yxym0UEtrBPIrUDL4/edit#heading=h.t9jqt8jtx531

Switching between the two sides should have a "rotate" transition from the SWT Transition Widget:
https://eclipse.org/nebula/widgets/stw/stw.php

The plugin should take this namespace: **info.limpet.stackedcharts.core**

Please create this feature in a new branch.

**Comment by theanuradha** [comment]
@IanMayo  I have setup projects with libs needed for "SWT Transition Widget" then try to run demos provide by "Nebula". seems on mac none of effects are working.

**Comment by IanMayo** [comment]
Ok, we've established that the widget does work under Windows & Ubuntu.  So, @theanuradha is going to invest a couple of hours in investigating the problem under OSX.

**Comment by theanuradha** [comment]
@IanMayo  I have added prototype switch mode with Transition effect. Please try and see effect works correctly on impl. [click on **'edit'** to switch mode] 

![image](https://cloud.githubusercontent.com/assets/535713/15148935/472c8898-16e5-11e6-96d5-fe98c5024cf9.png)

**Comment by IanMayo** [comment]
UI merged in #267 

Further development to be in branch for #261
