### ISSUE TITLE
Obtain some weather balloon data

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#263]
A weather balloon dataset would be useful in demonstrating the following aspects:
- having an independent axis that is something other than time, it will be **height** in this instance
- having a horizontal stack of graphs, necessary for **height** to go up the page, as would be logical

Ideally we'd have a CSV (or xslx) file of additional measured attributes, something like:
- altitude
- temperature
- pressure
- humidity

Note: while we may have time data in there, it's important that the first column is altitude, not time

**Comment by IanMayo** [comment]
@alexv8ss  - I know this isn't your background.  

But, when you run out of things to do in your other issues, or are waiting for me, could you do some googling to try to get at least one weather balloon ascent data-file?

**Comment by alexv8ss** [comment]
@IanMayo Ok Ian, right now I'm working at issue #266 analyzing small interesting cases, but as soon as I'm done, I'll help you out with this one too.

**Comment by IanMayo** [comment]
Aah, here's an Open Source example:
http://participatoryscience.org/data-activity/practice-asking-questions-balloon-ascent-data

**Comment by alexv8ss** [comment]
@IanMayo Perfect, I'll check it out and start working on it, do you have a deadline for this ?

**Comment by IanMayo** [comment]
No, no deadline whatsoever :-)

**Comment by alexv8ss** [comment]
Ok thanks @IanMayo currently having a though week, but I can work on this for sure. :)

**Comment by alexv8ss** [comment]
@IanMayo I've got this from the ballon analysis, check them out and let me know if that is what you were asking for. The graph analysis is not complete still, I have to read a little about the ideal gas law and try to model hellium as an ideal gas, and see if in this conditions Helium acts as an ideal gas. Let me know what you think about it. Cheers
[Ballon Ascent Graph Analysis.pdf](https://github.com/debrief/limpet/files/273746/Ballon.Ascent.Graph.Analysis.pdf)
[Balloon.xlsx](https://github.com/debrief/limpet/files/273747/Balloon.xlsx)

**Comment by alexv8ss** [comment]
@IanMayo I'm sending my analysis updated, please let me know your comments
[Ballon Ascent Graph Analysis.pdf](https://github.com/debrief/limpet/files/275693/Ballon.Ascent.Graph.Analysis.pdf)

**Comment by alexv8ss** [comment]
@IanMayo 2nd Analysis- Single Hydrogen Ballon Analysis, looks really similar to the single helium balllon analysis. Please check the final conclusion which I think it expains all the analysis sumarized in one parragraph. Cheers
[Single Hydrogen Ballon Ascent Graph Analysis.pdf](https://github.com/debrief/limpet/files/287712/Single.Hydrogen.Ballon.Ascent.Graph.Analysis.pdf)

**Comment by IanMayo** [comment]
Thanks @alexv8ss 

But, I've still got to catch up with the earlier reports.  So, please pause your analysis for a while, until I've added the ability to plot this data.

cheers,
Ian

**Comment by alexv8ss** [comment]
Ok @IanMayo  I'll continue working at issue #266

**Comment by IanMayo** [comment]
Done.
