### ISSUE TITLE
Produce example stacked graph without time as independent axis

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#266]
In explaining how stacked charts will work, I wish to provide an example where time isn't on the x-axis.

One example we could use for this would be to use speed on the x-axis.  For this to work, we to trim a dataset to a period of data where speed is increasing.  

So, could you use Excel (or something else) to produce a stacked graph showing speed against a range of other measurements. Hopefully they will be measurements that show some correlation to speed (throttle angle? fuel consumption?)

I will then use this graph image in my Stacked Charts document.

**Comment by IanMayo** [comment]
@alexv8ss - in the PDFs for the other issue (#259) you've produced graphs of speed vs something else.

These graphs aren't what I need for this issue.  Here is an example:
![speedvsrevs](https://cloud.githubusercontent.com/assets/1108513/15185866/b7159cc8-1792-11e6-8a28-a6b0e6bd7ad4.png)

This is Speed and Revs plotted against a counter.

What I need is for Speed to be on the x-axis, and for Revs to be on the y-axis.  This will let us see the relationship between Speed and Revs.

I know there isn't a direct relationship (because of the gears/transmission).  But, on an automatic, if the car "shifts up at 40 mph then we should see the revs regularly drop as speed goes from 39 to 41 mph.  That is us highlighting the relationship between speed and revs.

To do this, you may wish to choose a limited period of your data, covering a single long increase in speed.

You may also wish to choose a measurement that has a more direct correlation with Speed.

**Comment by alexv8ss** [comment]
Ian, I think I'm following you, just to put an example you need a graph like this?
![22-a](https://cloud.githubusercontent.com/assets/19258972/15190442/81bc3716-1775-11e6-96ea-963432dde38c.jpg)

**Comment by IanMayo** [comment]
No, that is two y axes.

Don't worry, this is a really complex concept. It took me ages to get it. The speed axis values have to run along the bottom.

I can try to produce an example tomorrow.

Sadly I can't think of an obvious example of this in normal life.

Ian

**Comment by alexv8ss** [comment]
Like this you mean? I have the X axis values as speed, and the y axis values as RPM. If not could you draw me a little sketch of what you are looking for? So I can help you get the graphs you need. The other graphs are correct? They are useful for you ?
![graph](https://cloud.githubusercontent.com/assets/19258972/15191986/c094a868-177c-11e6-876f-75b23fc99cea.jpg)

**Comment by IanMayo** [comment]
Yes, I'm pretty sure that's right.

For this specific issue, I'm looking for a stack of graphs. So, we'll shoot a range of measurements against speed. Right now, I'm not sure what measurements we have, and/or if they relate to speed.

If we do find some measurements to use, we would:
a) have measurements on both left and right hand y axes
b) have multiple graphs stacked vertically.

But, for now, let's concentrate on your other issue, where we get a general understanding of the data, measurements, and sensors.

**Comment by alexv8ss** [comment]
Ok I can try have multiple graphs stacked vertically and send it by today or tomorrow. I will keep logging and sending you the information

**Comment by IanMayo** [comment]
Cool, but don't bother about logging more data.  Let's gain an understanding of the current data.  Then we may decide we need to send you on a custom "trip" to produce data in a particular pattern.

**Comment by alexv8ss** [comment]
@IanMayo Some short analysis of an interesting case where the margin of error between the OBD and GPS speed is more than 90%
[Graph Analysis 3.pdf](https://github.com/debrief/limpet/files/273676/Graph.Analysis.3.pdf)

**Comment by alexv8ss** [comment]
@IanMayo Short analysis of variation of OBD vs GPS speed difference. I think I finally got it with the speed vs other data graph you were telling me. Please let me know your comments. 

[Speed error analysis.pdf](https://github.com/debrief/limpet/files/276162/Speed.error.analysis.pdf)
[trackLog.xlsx](https://github.com/debrief/limpet/files/276163/trackLog.xlsx)

**Comment by alexv8ss** [comment]
@IanMayo I upload Fuel consumption analysis. 

[Fuel Consumption Analysis.pdf](https://github.com/debrief/limpet/files/276491/Fuel.Consumption.Analysis.pdf)
[trackLog.xlsx](https://github.com/debrief/limpet/files/276492/trackLog.xlsx)

**Comment by IanMayo** [comment]
Before we can store this data in Limpet we need to be able to store non-time data as the independent dataset.

This is covered in #360

**Comment by IanMayo** [comment]
Done.
