### ISSUE TITLE
Create initial stack of charts

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#271]
Ok, we've now got a data model.

I'd like you to create a new branch off #261 , and start creating the "View" of the charts.

Here is a valid charts data object:
https://github.com/debrief/limpet/blob/bddc0db0fe6b55c062074edd38ce514acb79a690/info.limpet.stackedcharts.model.tests/testRead.stackedcharts

So, you can use the _testReadModel_ code from the ModelTests class to read in this datafile, and create a _ChartSet_ data object.

You can then create a stacked JFreeChart in the "view" pane of the stacked charts view.

@theanuradha - I've recorded some early thoughts here about how to handle model updates, and to help us think about the required listeners:
https://docs.google.com/document/d/1_IR773qKa9m4ZblFYd-m4WSW65yxym0UEtrBPIrUDL4/edit#heading=h.a48idc99w6cw

**Comment by theanuradha** [comment]
@IanMayo  as we plan on use JFreeChart, limpet projects seems not have bundle/plugin with  JFreeChart dependency. while **"org.mwc.cmap.jfreechart"**  on **debrief** what should we do include JFreeChart directly on **info.limpet.stackedcharts.core** ?

**Comment by IanMayo** [comment]
Aah, well spotted :-)

What we need to do is to make a copy of the Debrief plugin in the Limpet project.  

When StackedCharts RCP View gets included in the Debrief application it will link to the Debrief instance, and when it's in Limpet it will see the Limpet instance.

That's what we do with **org.geotools**

**Comment by theanuradha** [comment]
@IanMayo  I have push prototype version
![image](https://cloud.githubusercontent.com/assets/535713/15213422/b2183e24-1864-11e6-8142-3d78179f58e5.png)

**Comment by IanMayo** [comment]
Hey, nice work. That looks great :-)

**Comment by IanMayo** [comment]
Hi there,
the stacked_charts_poc now includes my code to populate the stacked charts.

You're aware that you still have some steps to take.  I'll have a play first think in the morning, and come up with a shopping list of further charting tasks for you.

**Comment by IanMayo** [comment]
@theanuradha - as you'll see, I've jumped ahead with this.

You can show my Tactical Overview chart using these steps:
- import info.limpet.sample_data to your runtime workspace
- Right-click on the _Overview.lap_ file, in the _Overview_ folder, and select _Open With_ /  _Data editor_
- Right-click on _Short Contact_, then _Analysis_ / _Show in Tactical Overview_

I'm sure you're aware of more JFreeChart tasks ahead of you.  

I've been adding some more custom styling to the charts, within #284.  
I've put some TODO marker in the ChartBuilder class - I'd like you to start with these please, ready for a demo on Wednesday.

Aah, hold on - I can't commit it for another hour or so.  I'll ping you when it's ready.

**Comment by IanMayo** [comment]
This is all working fine.
