### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#277]
I'm having trouble with the Travis build, largely since adding some new plugins. I've been working through the build errors in this branch:  **pom_build_fix**

My efforts so far are captured in PR: #275 

Here is the build transcript:
https://travis-ci.org/debrief/limpet/builds/129823559

Here is the error:  

Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:0.23.1:validate-version (default validate-version) on project org.mwc.cmap.jfreechart: OSGi version 1.0.21 must have .qualifier qualifier for SNAPSHOT builds -> [Help 1] 
 [ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:0.23.1:validate-version (default-validate-version) on project info.limpet.stackedcharts.model: Unqualified OSGi version 0.1.0.qualifier must match unqualified Maven version 1.0.6-SNAPSHOT for SNAPSHOT builds -> [Help 1]

**Comment by theanuradha** [comment]
@IanMayo https://github.com/debrief/limpet/pull/278

**Comment by IanMayo** [comment]
Fixed in #278
