### ISSUE TITLE
Combine stacked charts editor & view controls

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#281]
The two faces of the stacked charts are currently being developed in separate plugins.

We should rationalise them into an **info.limpet.stackedcharts.ui** plugin.

Once this is resolved, update the static code analysis in #279 

@theanuradha - let's not do this until @dinkoivanov has converted the editor to an SWT Control.

**Comment by IanMayo** [comment]
@theanuradha - Dinko has changed the editor into a control, and has integrated it into the API.

But, I think it has introduced a delay in opening the view.

Could you do some testing, just to confirm if it does introduce a delay.

Since the editor isn't visible to start with, we could lazily load it - either:
1. after the **build()** is complete
2. when the edit panel is first opened.

If the GEF editor is introducing a delay, could you implement one of the above?  I think I prefer (1.), but am ok with (2.) if (1.) is technically difficult.

**Comment by theanuradha** [comment]
https://github.com/debrief/limpet/pull/297

**Comment by IanMayo** [comment]
Delay fixed.  We now just have to refactor the two plugins into one _stackedcharts.ui_

**Comment by IanMayo** [comment]
@dinkoivanov - is there anything that @theanuradha  should be particularly careful about when moving your stackedcharts.editor code into his plugin?

Anything unusual about the implementation?

I wouldn't think so :-)

**Comment by dinkoivanov** [comment]
@IanMayo: I can't think of anything special. Should be safe.

**Comment by theanuradha** [comment]
https://github.com/debrief/limpet/pull/303

**Comment by IanMayo** [comment]
Closed in #303
