### ISSUE TITLE
GEF editor polishing

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#282]
Here's a prioritised shopping list of improvements to the GEF editor:
- [x] resize editor to fit view size
- [x] ensure editor is in a SWT Control (to go into the rotating transition parent)
- [x] slight grey shading to each chart, with white padding/margin between them
- [x] make shared x axis selectable
- [x] add "x" button to "remove this dataset" from an axis (this is to "force" a large data change in the view)
- [ ] If no axes at end of chart, create "Landing pad" - so we can drop an axis onto it

**Comment by IanMayo** [comment]
Shopping list reformatted to make items clickable, so @dinkoivanov can indicate progress.

**Comment by dinkoivanov** [comment]
I though that white chart on a grey background would better resemble the JFreeCharts output, so I did it this way: 
![capture](https://cloud.githubusercontent.com/assets/4459598/15347992/52d7d284-1ccf-11e6-82ee-6bbc0103d6fc.PNG)
Let me know however if you would still want grey shading with white padding between them.

**Comment by IanMayo** [comment]
Good choice of colours. But, could you make the borders/margins larger?

I guess they should be double the current size.

**Comment by dinkoivanov** [comment]
Margins are doubled now, the X button removes the dataset from the axis only, note that the dataset still remains in the ChartSet. My suggestion is to check if no other axis uses this dataset, then remove it from the ChartSet as well.
I guess Undo/Redo would be good - should not be a bid deal to implement - GEF already provides the actions, just need to be bound to the corresponding Eclipse commands.

**Comment by IanMayo** [comment]
Not at pc now. But, I think I removed datasets from chartset , to make it easier for me to generate data files using xml editor.

**Comment by IanMayo** [comment]
This is all going fine. The unresolved issues are not in other issues.
