### ISSUE TITLE
Introduce more advanced styling

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#284]
- [x] introduce color property for a dataset
- [x] set colors for TacticalOverview
- [x] user markers & colors in JFreeChart ( for @theanuradha  ) 
- [x] introduce time markers, as in the sample datasets

**Comment by IanMayo** [comment]
I've got to submit the correct version of the EMF Model code, it's wrongly formatted on this laptop.

I'll push it as soon as I can, and merge into stacked_charts_poc.  The I'll ping you :-)

**Comment by IanMayo** [comment]
Ok, @theanuradha  my completed bits are now in **stacked_charts_poc**

Stacked Charts View is now supplied with model data that includes styling.  It's probably rubbish styling, but it's in there :-)

**Comment by IanMayo** [comment]
Ok @theanuradha - we're jumping forward :-)

I've made some more changes, and this time I've pushed the Branch to your repo, so you can extend it properly. It's called: **284_advanced_styling_c**

This is a plot for **short_groupByType.stackedcharts**:
![stackedview](https://cloud.githubusercontent.com/assets/1108513/15288672/58c3d024-1b64-11e6-99ff-34a7f3708c3f.png)

The ChartBuilder requires the following mods:
- [ ] The index used for per-series formatting isn't incrementing correctly. It's incrementing for each axis. It should increment for each series.  That is why many datasets in the plot have the wrong color/marker (the Pri series should be blue, and the Sec series should be red)
- [ ] We need to add multiple axes to the plots.  The datasets in the XML files have the correct MinAxis & MaxAxis organisation.

**Comment by theanuradha** [comment]
@IanMayo  I think I got it :-)

![image](https://cloud.githubusercontent.com/assets/535713/15298561/880e1e30-1bbd-11e6-9470-15d4e6ff664c.png)

![image](https://cloud.githubusercontent.com/assets/535713/15298577/97f125f4-1bbd-11e6-9525-e45b2588e6f7.png)

![image](https://cloud.githubusercontent.com/assets/535713/15298585/a418096a-1bbd-11e6-93a3-43d2d9776fa5.png)

**Comment by IanMayo** [comment]
Good progress with the secondary axes - well done.

But, the "pri_course" and "sec_course" datasets should be visible on the **Course** chart in the bottom two examples.

**Comment by theanuradha** [comment]
https://github.com/debrief/limpet/pull/293

**Comment by theanuradha** [comment]
@IanMayo I will look in to it

**Comment by IanMayo** [comment]
Oh, the dataset formatting still isn't right.  I'm sure **pri_depth** should be blue.

Also,for the lower (relative) chart - it looks like all of the datasets are on the "range" axis. Bearing, Rel Bearing and ATB should all be on the **Bearing** axis, and **Bearing Rate** should be on the **Bearing rate** axis.

**Comment by theanuradha** [comment]
@IanMayo  Just push a fix but seems colors are off  

![image](https://cloud.githubusercontent.com/assets/535713/15299257/37b549b4-1bc1-11e6-9c7c-04e79ae1aa66.png)

**Comment by IanMayo** [comment]
Closer.  But, I can see that the **Range** dataset has been put on the **Bearing** axis.

If you open the relevant **'*.stackedcharts** datafile in IDE mode using eclipse's XML editor you can visually check that the datasets are plotted against the correct axis.

**Comment by theanuradha** [comment]
@IanMayo yes doing that now also styles seems off now.

**Comment by theanuradha** [comment]
@IanMayo checking still but seems lot close at least styles now on track 

![image](https://cloud.githubusercontent.com/assets/535713/15299751/58f641e4-1bc3-11e6-84fc-fb4fc7404055.png)

**Comment by theanuradha** [comment]
@IanMayo  seems looks good now please review and let me know.

**Comment by theanuradha** [comment]
on Zoom
![image](https://cloud.githubusercontent.com/assets/535713/15300017/51b464b4-1bc4-11e6-853f-5886ccd41045.png)

**Comment by theanuradha** [comment]
@IanMayo  if this is good I assume we need marker/annotation support

**Comment by IanMayo** [comment]
Hmm, aren't the "Pri" tracks in Blue in the datafile?

**Comment by theanuradha** [comment]
@IanMayo  "Pri_Speed" is red color="#FF0000"

**Comment by theanuradha** [comment]
sec_speed is color="#0000FF"

**Comment by IanMayo** [comment]
Aah, ok. My mistake (not at a desktop).  

I can't see "Range" or "ATB" datasets on the bottom chart. They're in the key - but not on the chart. I would expect the Range axis to be in the 000's.

**Comment by theanuradha** [comment]
@IanMayo  **"Range"** is on chart 

![image](https://cloud.githubusercontent.com/assets/535713/15309316/89b8ca1e-1c03-11e6-89a3-5ee4324bcf91.png)

**Comment by theanuradha** [comment]
**ATB**

![image](https://cloud.githubusercontent.com/assets/535713/15309368/f5142dbc-1c03-11e6-9ed4-deeb2b73e5ba.png)

**Comment by IanMayo** [comment]
@theanuradha- Range should be plotted on the range axis- not the bearing axis.

**Comment by IanMayo** [comment]
Fixed in #293

**Comment by IanMayo** [comment]
Re-opening, to cover the adding the time markers.

@theanuradha - I suggest it goes in a branch called 284_styling_markers.

**Comment by theanuradha** [comment]
@IanMayo added support for both selective annotations $ axis annotations 

screenshot selective annotations on **SharedAxis**
![image](https://cloud.githubusercontent.com/assets/535713/15324024/4a5b30f0-1c62-11e6-87b9-af4e72ecf39f.png)

TODO: ScatterSet Marker impl in JfreeChart

**Comment by theanuradha** [comment]
https://github.com/debrief/limpet/pull/296

**Comment by theanuradha** [comment]
@IanMayo  any input on ScatterSet what do you expect ? 
Following are JfreeChart support Markers so not sure how we add ScatterSet
![image](https://cloud.githubusercontent.com/assets/535713/15324204/20cae748-1c63-11e6-8358-22e6856168e5.png)

**Comment by IanMayo** [comment]
Initially, the scatter set will be a series of Markers on that axis.  Like the simple line marker in your last screenshot.

In the TacticalOverview datasets in the repo - they will be a set of vertical lines, on Chart Zero.

**Comment by theanuradha** [comment]
@IanMayo so Only first line will get Label then ?

**Comment by theanuradha** [comment]
@IanMayo  Just added ScatterSet Support 
![image](https://cloud.githubusercontent.com/assets/535713/15325328/b098d1ec-1c67-11e6-8c38-575390225a7b.png)

**Comment by IanMayo** [comment]
Let's not provide a label. Let's just provide the series of vertical lines.

Yes, your implementation is fine.  Here is a mockup of what we were hoping for.

Have you put the scatterset on the correct graph?  The scatter-set has an "Appears in" element.

![incontacttime](https://cloud.githubusercontent.com/assets/1108513/15325369/1d8ed5ec-1c42-11e6-9f87-5ce504bbf8db.png)

**Comment by IanMayo** [comment]
Markers added in #296
