### ISSUE TITLE
Support ChartOrientation in Editor

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#294]
Just capturing this, so it doesn't fall through the gaps.

Anu's Chart Viewer adjusts according the ChartSet's Orientation attribute.

We should also support it in the editor.  I see this as a two-phase process:
- [x] Provide **Orientation** as an editable property for the chart-set
- [ ] Make the Chart Editor re-arrange its layout to reflect the orientation attribute.  Note, two "Helper" classes may help this - one for Horizontal & one for Vertical. That should let you keep the rest of the control flow & logic relatively unchanged.

**Comment by dinkoivanov** [comment]
Could you elaborate a bit more on the "Helper" classes idea?

**Comment by IanMayo** [comment]
Sure, imagined an interface with methods such as"buildAxis". There would be two implementing classes: horizontal and vertical. The helper would encapsulate all the small details of horizontal vs vertical layout, leaving your remaining GEF code clean of these details.

Just a suggestion :-)

## Update

Hmm, have just looked at a list of Design Patterns ( [patterns page](http://www.fluffycat.com/Java-Design-Patterns/)  ), and can't find a pattern that matches the "helper" instances I'm describing. Sorry

**Comment by IanMayo** [comment]
Any chance of a couple of screenshots @dinkoivanov  - I'm dying to see it

**Comment by dinkoivanov** [comment]
This is the current state, few small layout issues. Once fixed I think the code needs some cleanup. It makes sense to come up with custom layout container (draw2d figure) that's able to switch from horizontal to vertical layout. That is from aligning its children in a row to aligning the children in a column.
![capture](https://cloud.githubusercontent.com/assets/4459598/16106079/b0cb2144-3399-11e6-8bcd-ee07675b853c.png)

**Comment by dinkoivanov** [comment]
Summary of leftover alignment issues:
- [x] Center vertically dataset figures when stack is vertical
- [x] Center horizontally chart header figures when stack is vertical
- [x] Center horizontally shared axis figures when stack is vertical
- [x] Center horizontally dataset figures when stack is horizontal
- [x] Center vertically chart header figures when stack is horizontal
- [x] Center vertically shared axis figures when stack is horizontal
- [x] Center horizontally axis figures when stack is horizontal
- [x] Upon orientation switch (hor/ver), the shared axis figure is not refreshed (appears too big until refresh)
- [x] Scatterset landing pad is missing, when stack is horizontal
  ![capture](https://cloud.githubusercontent.com/assets/4459598/17647801/7485e7ca-6209-11e6-8e9a-e29785660d3b.PNG)

**Comment by dinkoivanov** [comment]
@IanMayo Should be OK now, let me know if you experience any problems when switching between horizontal & vertical layout
