### ISSUE TITLE
Introduce IndependentAxisController

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#295]
In the Debrief context, we wish to show a vertical marker at the "current time".  Well, not the current time, but the time that Debrief is currently highlighting data at.

![timecontroller](https://cloud.githubusercontent.com/assets/1108513/15322610/c0897eda-1c35-11e6-973d-2226830882f8.png)

Note the two white rectangles in the screenshot.  They show the two ships' positions at 11:30 on 12th December 1995.

When looking at a Tactical Overview (or other stacked charts) in Debrief, we should draw a vertical line on the time (independent) axis at this time. So, as the user moves backwards & forwards it's possible to scan through the stacked charts & see what is happening at each time.

My first idea for this is to let the current "Data Converter" / "Data Provider" helper class have an "addMarkerListener" method. This will receive a property change listener, that, when called, draws a vertical marker at the supplied value on the independent axis.

Note: I'm deliberately trying to be non time specific, to allow for other measurements to be used as the independent axis: like "altitude" being used for a weather balloon ascent.

**Comment by IanMayo** [comment]
Hey, @dinkoivanov & @theanuradha - do you have any thoughts/opinions on this?

I'm sure @theanuradha will find it easy enough to implement.  But any other thoughts welcome.

cheers,
Ian

**Comment by dinkoivanov** [comment]
I like the marker listener idea. Another option would be the Time Controller to be a selection provider for the Site (in Eclipse RCP terms). When time marker, it will notify interested parties with selection changed event, wrapping the time value. On the other hand, the tactical overview and other stacked charts can listen to selection changes and respond appropriately (https://wiki.eclipse.org/FAQ_How_do_I_make_a_view_respond_to_selection_changes_in_another_view%3F)

**Comment by IanMayo** [comment]
Thanks for those thoughts.  I'm nervous about using Selection to propagate time changes, since the Properties View responds to the current selection.  I think the user may be _surprised_ to see the item in the Properties View change when they move the time slider.

Hmm, or, it may work to the user's advantage.  If "time now" is displayed on the Properties View then the user can manually enter a time to jump to that time.

But, the down-side of the current selection being replaced when a non data-item is manipulated seems a greater loss.

**Comment by IanMayo** [comment]
Closed, in #253
