### ISSUE TITLE
Update Limpet feature dependencies, ready for build

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#298]
Our Limpet product definition doesn't include the correct dependencies.

Well, it includes the right features, but the features don't include the right plugins.

Once the stacked charts UI plugins have been refactored into one plugin, we should update the feature/plugin dependencies so we have a tidy build definition.

**Comment by theanuradha** [comment]
https://github.com/debrief/limpet/pull/303
this PR cover this too

**Comment by IanMayo** [comment]
Closed in #303

**Comment by IanMayo** [comment]
@theanuradha - I think we still have some missing plugins in the build.

The Travis build updates the p2 repository at the update site:
http://debrief.github.io/limpet-update/1.0

But, when I do an update (from the last "release", which was back in Dec 2015) I get these missing plugins:
![missingplugins](https://cloud.githubusercontent.com/assets/1108513/15392102/ffd78810-1dbc-11e6-983f-d64e67616ff2.png)

Could you verify if/where they should be included?

**Comment by theanuradha** [comment]
@IanMayo  this is now fixed
