### ISSUE TITLE
Allow per-plugin versioning for Tycho build

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#299]
Our Travis (maven) build appears to depend on all plugins sharing the same version.

However, I wish our plugins to have different versions, and be updated individually (as necessary).

I know the Debrief build process allows for this, including a command to sync the POM versions with the relevant plugin version: (documented here)[https://github.com/debrief/debrief/wiki/Getting-started-in-Debrief-development#maven-update-versions]

Could you update our build definition/script/process so that we allow plugins of different versions in the main project build?

**Comment by theanuradha** [comment]
https://github.com/debrief/limpet/pull/306

**Comment by theanuradha** [comment]
@IanMayo  we can close this.

**Comment by IanMayo** [comment]
Great thanks - closed in #306
