### ISSUE TITLE
GEF Editor properties not being shown

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#308]
When the GEF editor was in its own plugin it presented a single property: the **Name** for a **Chart**.

But, now that the plugins have been combined - and the GEF Editor is no longer in its own EditorPart, we aren't getting any properties.

Once the [Debrief Build](https://github.com/debrief/debrief/issues/1756) issue is resolved, could you investigate this?

**Comment by theanuradha** [comment]
https://github.com/debrief/limpet/pull/310

**Comment by IanMayo** [comment]
Thanks, will review tomorrow morning

**Comment by IanMayo** [comment]
Fixed in #310
