### ISSUE TITLE
Introduce Undo/Redo for GEF editor

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#316]
As previously discussed, it would be good to support undo in our GEF editor.

Could you add it?

**Comment by IanMayo** [comment]
Hi there, just had a play with undo/redo.

It's working fine, but we have a UX issue with it.

The undo/redo buttons are enabled when we're in "View" mode, but the changes aren't updated on the View chart.

I guess we have a couple of options:
1. only enable the buttons when in Edit mode
2. only show the buttons when in Edit mode
3. add the Chart Builder as a high-level listener, so it redraws when any undo/redo operations are performed
4. generate discrete listener capabilities, so parts of the chart are updated when their respective model element is modified.
1. Seems inconsistent, since the user won't necessarily know why the buttons aren't enabled
2. Is more consistent, but the user may only decide to undo when the get to the View mode
3. Seems easy.  We haven't encountered any performance challenges yet.  If/when we do, we may seek to minimise the parts of the ChartSet that get updated.
4. Seems like the most work, with some fragility.  But, it does seem the correct route to take if we ever merge the View/Edit modes.

Any thoughts @dinkoivanov ?

**Comment by dinkoivanov** [comment]
Agree, 2 will be easiest, relevant in short term. 3 is not that much work actually compared to 4. A generic listener could easily be added using EContentAdapter like described here: http://www.vogella.com/tutorials/EclipseEMFNotification/article.html#emfnotifcation. The solution with fine granular event handling (4) will require most effort.
The chart builder will actually listen for model changes (which Undo/Redo operation trigger) and then update the corresponding JFreeChart. And there won't be a need to rebuild the chart when you switch from Edit to View, it would be built just once.

**Comment by IanMayo** [comment]
**Generic Listener**

do all changes get propagated up to the top-level ChartSet object?  If it doesn't, then it seems the ChartBuilder would have to register to listen to all of the discrete EMF model objects.  Or, our Command instances will have to call some "fire notify" event after making a model change.

Can you explain the implementation in a bit more detail?

**Comment by dinkoivanov** [comment]
That's the difference between using an Adapter and EContentAdapter. The former will only listen for changes to the object you've registered the adapter in, while the EContentAdapter will be notified for any change in the object hierarchy. For example adding it to a ChartSet:

```
    EContentAdapter adapter = new EContentAdapter() {
      public void notifyChanged(Notification notification) {
        super.notifyChanged(notification);
        int featureId = notification.getFeatureID(StackedchartsPackage.class);
        System.out
            .println(featureId);
      }
    };
    getChartSet().eAdapters().add(adapter);

```

will get us notified about for example deletion of a dataset.

**Comment by IanMayo** [comment]
@dinkoivanov - I came across this issue again today.  When in the View mode, we can see the Undo button, and we can force an Undo.  But the view mode chartbuilder doesn't redraw.

Could you trigger a chart redraw on Undo/Redo in the View mode please?   (this looks like _Option 3_ in the original list).

**Comment by IanMayo** [comment]
Resolved.
