### ISSUE TITLE
Provide Preview chart in GEF Editor

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#317]
- [ ] use the new ChartBuilder.createChart() method to create a preview chart in each edit window
- [ ] Make the new preview charts update as necessary

**Comment by theanuradha** [comment]
![image](https://cloud.githubusercontent.com/assets/535713/15553308/0525323a-22dc-11e6-922b-f284a498daed.png)

**Comment by IanMayo** [comment]
wow! brilliant!

**Comment by IanMayo** [comment]
First version merged in.

Keeping the issue open, for @theanuradha  to work on behind-the-scenes optimisation & tidying.

**Comment by IanMayo** [comment]
Working ok. Will trap enhancements as they arise.
