### ISSUE TITLE
Avoid JFreeChart scaling by setting very large max size

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#322]
As JFreeChart charts controls become larger, after they reach a certain size, JFReeChart stops resizing the chart itself, it just stretches a bitmap representing the chart.

Here is a stacked charts at a small size:
![normal](https://cloud.githubusercontent.com/assets/1108513/15579158/4e90c6a8-235b-11e6-954d-2d6960b699ac.png)

Here is one that has been vertically stretched, note how the plots have stopped being resized, but JFreeChart has just stretched the image:
![stretched](https://cloud.githubusercontent.com/assets/1108513/15579176/667b3e38-235b-11e6-8b09-ed618ca6825b.png)

I'm pretty sure this image is as described here:
http://www.jfree.org/phpBB2/viewtopic.php?f=3&t=13401

http://stackoverflow.com/questions/5803991/how-can-i-have-a-jfreechart-chartpanel-automatically-enlarge-itself

We've overcome this issue in Debrief's XYPlot plugin, but I can't now find the code. Here is a tall XYPlot view:
![xyplot](https://cloud.githubusercontent.com/assets/1108513/15579218/9c803bbe-235b-11e6-9b9a-7247382c02bc.png)

Note how the text in the key hasn't been stretched tall.

My users have monitors about 30", capable of about 2560 x 1440 - so JFReeChart needs to draw at native resolution up to sizes like these.

**Comment by theanuradha** [comment]
https://github.com/debrief/limpet/pull/323

**Comment by IanMayo** [comment]
Fixed in #323

**Comment by IanMayo** [comment]
Fixed.
