### ISSUE TITLE
More GEF editor steps

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#330]
This issue records some outstanding items necessary in the GEF editor
- [x] **Add Chart** - a button by the "ChartSet" label, to add a new blank chart
- [x] **Axis landing pad**  - if a chart doesn't have any axes at an end, display a "landing pad" rectangle where axes can be dropped
- [x] **Re-order charts** - drag/drop a chart onto another, to appear before it in the order
- [x] **Delete chart** - an "x" button next to the chart title, to delete it

**Comment by theanuradha** [comment]
@IanMayo 
- [x] Delete chart - an "x" button next to the chart title, to delete it  ->https://github.com/theanuradha/limpet/commit/910b38f81c2c7b81592353957b6a6b0dcc693509
- [x] Axis landing pad - if a chart doesn't have any axes at an end, display a "landing pad" rectangle where axes can be dropped -> https://github.com/theanuradha/limpet/commit/c3e8e290edadc0d5c21a2852492c150b2336ea05

**Comment by theanuradha** [comment]
@IanMayo 
- [x] Re-order charts - drag/drop a chart onto another, to appear before it in the order -> https://github.com/theanuradha/limpet/commit/af81c14fc0ed86ccadf267002ab490830cf99d2f

**Comment by theanuradha** [comment]
- [x] Add Chart - a button by the "ChartSet" label, to add a new blank chart ->https://github.com/theanuradha/limpet/commit/dccf8712a20a517dbdc87dfc1227c309f992914f

**Comment by theanuradha** [comment]
https://github.com/debrief/limpet/pull/333

**Comment by IanMayo** [comment]
cool, could you give me a screenshot with the new features?

**Comment by theanuradha** [comment]
![image](https://cloud.githubusercontent.com/assets/535713/15685432/481eba3c-2789-11e6-8551-c8f49a63e24c.png)

![image](https://cloud.githubusercontent.com/assets/535713/15685446/59565d46-2789-11e6-8ac1-6812a750b2bd.png)

**Comment by theanuradha** [comment]
DnD feature not possible to catch via screenshot sorry

**Comment by theanuradha** [comment]
This is added new chart via **'+'**  and then drop Axis to it landing 
![image](https://cloud.githubusercontent.com/assets/535713/15685486/87aaf40e-2789-11e6-9983-e91c4420e720.png)

![image](https://cloud.githubusercontent.com/assets/535713/15685498/9ebf09f0-2789-11e6-8fb6-3711a438226d.png)

**Comment by IanMayo** [comment]
Closing this, now that remaining item have been moved to other issue.
