### ISSUE TITLE
Strategy for dataset updates

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#332]
In both the Debrief and Limpet contexts we will need our Stacked Charts to dynamically update as the parent data is modified.

For both contexts I expect we will have "adapter classes" that produce Stacked Charts datasets from the real data. At this stage, the adapters could add a listener to the original object, and fire some update on the dataset after any modification.

The chart builder would register as a listener for such an update, and reconstruct the JFreeChart data collection.

The EMF model API does have a "notify" event that is called on every modification to a Dataset object.  But, this seems to broad-brush for our requirement.

So, maybe we can perform some customisation of the existing notify() event propagation (with a custome **Notification** object).  Or we could declare our own API extension to Dataset, something like this:

```
   void addModifiedListener(PropertyChangeListener listener);
   void fireModified(PropertyChangeEvent event;
```

Do you have any feelings on this @dinkoivanov ?

**Comment by dinkoivanov** [comment]
I assume the chart builder would indeed need to reconstruct the JFreeChart data collection every time a Dataset changes. Could you clarify why you think the EMF model API could be a broad-brush?
If you see the DatasetEditPart, the adapter there already listens for changes in the Dataset. I imagine it can also listen for StackedchartsPackage.DATASET__MEASUREMENTS changes in order to get changes in the collection of data items.

**Comment by IanMayo** [comment]
We may choose to update the whole JFreeChart chartset, or just the specific collection for that dataset.

I was nervous that unrelated changes would trigger the notify, and cause unnecessary chart repaints.

But, we can try just using notifications.  I'll try it next week.

**Comment by IanMayo** [comment]
Ian - now we can drag/drop Limpet datasets into the Stacked Charts, make the JFreeChart dataset dynamically update when the Limpet dataset is modified.

Note, if we create a listener, we will also have to destroy it.

**Comment by IanMayo** [comment]
Datasets now update
