### ISSUE TITLE
Limpet operation to create stacked charts

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#334]
To give us more variety in how we drive the stacked charts, we should integrate general stacked charts into Limpet. We currently have test for the Tactical Overview, but we should also drive general stacked charts.

The support should be via both a right-click Limpet operation, and drag/drop of datasets into an existing stacked chart.

Once this is done, invite @bcpeters3 to perform a usability review.  @alexv8ss may also have opinions.
## Update

Part one is complete, we can create them.  But, it still requires this:
- [x] add drag/drop of datasets onto the axis of a stacked chart editor pane (using a registered adapter)
- [x] allow folders and datasets to be selected, work down through folders to create items

Once #334 is merged in, we should update this branch (334_create_stack_operation), then carry on with the above steps.

**Comment by IanMayo** [comment]
@theanuradha - I could do with a helping hand, here, please.

I need to configure drag/drop from our Outline view to the Stacked Charts editor.

Here are the steps to prepare the data:
- open **overview.lap** in the sample_data/data folder
- the Limpet editor will open
- right-click on _ShortContact_ and select **Analysis**/**Show in tactical overview**
- switch the stacked charts to edit view
- open the **ShortContact/Primary** folder
- drag **Pri_Speed** onto the editor

At this point, I want Limpet to capture the drag event, and offer Yes/No feedback on if the dataset is suitable. If the dataset is suitable, then when it is dropped, the data will be converted, and added to the target chart/axis.

The new **AdapterRegistry** class will support this, together with the new **LimpetStackedChartsAdapter** class.

I'm quite ok with doing the conversions, and testing the data, but I'm stuck on how/where to register the drag/drop handler for the StackedCharts editor.  So, I just need your support in the RCP drop/drop handlers.

Would you mind adding this implementation to the branch I've pushed to your repo?
https://github.com/theanuradha/limpet/tree/334_create_stack_operation

cheers,
Ian

**Comment by theanuradha** [comment]
@IanMayo  Im on it

**Comment by IanMayo** [comment]
Fixed in #340

**Comment by IanMayo** [comment]
Re-opening, and assigning to @theanuradha - to handle the drag-over feedback for if an axis can accept particular types of data.
