### ISSUE TITLE
Flicker on Stacked Charts rotate transition

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#337]
@IanMayo commented on [Wed Jun 01 2016](https://github.com/debrief/debrief/issues/1777)

When we go from View to Edit (on Win/Linux) we briefly see a "freeze frame" of the destination panel before the transition starts.

We shouldn't see this effect.

**Comment by theanuradha** [comment]
https://github.com/debrief/limpet/pull/354

**Comment by IanMayo** [comment]
Fixed.

**Comment by IanMayo** [comment]
@theanuradha - the final solution has been accepted by Nebula, though it may be some time before it appears in builds.

Could you switch our implementation to the final version, and test it works ok?

https://bugs.eclipse.org/bugs/show_bug.cgi?id=499293

**Comment by theanuradha** [comment]
@IanMayo I will

**Comment by theanuradha** [comment]
https://github.com/debrief/limpet/pull/397

**Comment by IanMayo** [comment]
Ooops, I may spoken too soon.  Rodrigo said may actually be further changes.  I'll check.

**Comment by theanuradha** [comment]
no I check they marge to master code base in Nebula primary repo.  I took changes from there

**Comment by IanMayo** [comment]
I'm sure this is fixed now.
