### ISSUE TITLE
Introduce Stacked Charts icons

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#341]
We now have a set of 16px icons to use in the stacked charts (attached).

[StackedChartsIcons.zip](https://github.com/debrief/limpet/files/304300/StackedChartsIcons.zip)

We need to modify our GEF editors to use these icons instead of the "Axis", "Chart", "Dataset", etc labels.

Two sets of icons are provided: one in Limpet colors, and one in B&W.   Please make the first version use a combination of both sets, so we can make a decision on which one is more clear.

The change will be applied in a fork of the **stacked_charts_poc** branch.

**Comment by theanuradha** [comment]
![image](https://cloud.githubusercontent.com/assets/535713/15918764/08284984-2e28-11e6-8e9c-4ddd387972a6.png)

BLACK Icons

![image](https://cloud.githubusercontent.com/assets/535713/15918773/2f3c6956-2e28-11e6-83fe-22d3b8c37dd7.png)

**Comment by theanuradha** [comment]
@IanMayo note that icon set missing **dataset** icon, I have use paint for now

**Comment by theanuradha** [comment]
https://github.com/theanuradha/limpet/commit/e2053b3321bd6ff626ba6720b4c52f7551c7770c

**Comment by theanuradha** [comment]
https://github.com/debrief/limpet/pull/345

**Comment by IanMayo** [comment]
@theanuradha - I've done some tidying, but have got stuck.  I've added the Axis icon to the Shared Axis at the bottom of the editor.

But, I can't align them properly.  I'd like the icon & text to be centred in the Shared Axis, but they're stuck on the left:
![labelalignment](https://cloud.githubusercontent.com/assets/1108513/15923510/924f8ba2-2e25-11e6-9a4a-e24edb77dcd2.png)

If/when you get chance, I'd appreciate you fixing my Draw2D layout code in _SharedAxisEditPart_, please.

**Comment by theanuradha** [comment]
@IanMayo  done

**Comment by IanMayo** [comment]
Oooh, @theanuradha  - I look forward to having your Draw2D skills, one day...
