### ISSUE TITLE
Support for empty Stacked Charts View

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#355]
We currently build stacked charts by "pushing" datasets from a data-oriented tree view.

But, I also wish to allow a user to open a blank Stacked Charts view. The view will open in edit mode with a single graph showing min/max placeholders.

When the user drags in a dataset, the time data will be used for the shared axis.

**Comment by dinkoivanov** [comment]
@IanMayo: Change submitted, note that when user have the Stacked Charts view open and restarts the workbench, it appears blank/uninitialized. We might need to handle that (some kind of persistence?)

**Comment by IanMayo** [comment]
This is working fine, I've tried it repeatedly.
