### ISSUE TITLE
Stacked Chart - let course axis display +/- 180

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#375]
When vehicles are travelling close to North, the course graph unnecessarily jumps between 0/360.  But, if the graph is presented as +/- 180 then the data stays together.

![before](https://cloud.githubusercontent.com/assets/1108513/17179305/a0e5b27a-5410-11e6-960e-e1f97e129c3f.png)

Note how the blue line alternates between the top & bottom of the plot near the start.

**Comment by IanMayo** [comment]
Model changes complete, in branch: https://github.com/theanuradha/limpet/tree/375_course_180

But, the AxisType (that AngleAxis extends) is a child property of the AbstractAxis object:

![axistype](https://cloud.githubusercontent.com/assets/1108513/16985605/7fbeb444-4e79-11e6-99bd-4e0df5dcdabb.png)

In our property editor, we expose the properties for the AbstractAxis, not the AxisType.  We could provide separate UI element for the user to click on, but this would not be good UI.  Really we need to combine the properties of AbstractAxis and it's child AxisType element into one list.

I'd like to pass this to you, please @theanuradha  

Once the user can control the Angle properties (including min/max/midOrigin), I will return to the issue, to allow users to indicate that the range should be (min-range/2) to (min+range/2)

You  can get to the relevant editor for this by opening Overview.lap, then right-clicking on **LongContact** and selecting **Analysis/Show in Tactical Overview**.  Then switch to edit mode, and select **Course (Degs)**.  The axis properties will be shown in the Properties window.  We wish to see the child AxisType properties in the list too.

**Comment by theanuradha** [comment]
@IanMayo  after long  and deep dive in EMF & GEF code I did it . will cleanup code and crate PR

![image](https://cloud.githubusercontent.com/assets/535713/17135782/0968d510-534f-11e6-8092-6927f1131a73.png)

**Comment by theanuradha** [comment]
https://github.com/debrief/limpet/pull/380

**Comment by IanMayo** [comment]
Hey, nice work.  Minor suggestion:  is it possible to group them using category values?  I guess they could logically be grouped according to "Core" and "Styling".

Hey, @dinkoivanov - look what @theanuradha has managed to do, to combine the properties of an object and its child in one properties view!

**Comment by theanuradha** [comment]
i will look on grouping

**Comment by theanuradha** [comment]
@IanMayo 
![image](https://cloud.githubusercontent.com/assets/535713/17151031/7eba92dc-538f-11e6-9b3a-429dba39e00b.png)

**Comment by theanuradha** [comment]
@IanMayo  I have push changes but git hub not showing it on website or PR. 

![image](https://cloud.githubusercontent.com/assets/535713/17151280/b8dc10ac-5390-11e6-9c44-b3e9be0d00e1.png)

**Comment by theanuradha** [comment]
@IanMayo  OK it is now 👍

**Comment by theanuradha** [comment]
https://github.com/debrief/limpet/pull/380

**Comment by dinkoivanov** [comment]
Nice work indeed!

**Comment by IanMayo** [comment]
Fixed in #382

**Comment by IanMayo** [comment]
Fixed version:
![after](https://cloud.githubusercontent.com/assets/1108513/17179340/bdbca9a8-5410-11e6-82fd-6f2ee17d2d4e.png)
