### ISSUE TITLE
Move Data Manager to being an editor

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#38]
Data Manager is currently a view.

For standalone limpet we're going to use it as an editor.  

Could you convert it to an editor?

Once it's an editor, we can start work on XML persistence (#22).

**Comment by pecko** [comment]
@IanMayo I suppose you mean Data Provider

Notice:
All views/editors (Data Provider, Data Frequency, Analysis view) requires icon.

**Comment by IanMayo** [comment]
Data Provider - yes.

I'm building up a shopping list of icons.

**Comment by pecko** [comment]
We will use .lim extension. Agree?

**Comment by IanMayo** [comment]
No, let's go for .lap (Limpet Analysis Project)

**Comment by pecko** [comment]
OK. What you mean that we create multipart xml editor with two pages:
- standard xml source editor
- limpet form editor

I will create some placeholder editor similar your view for now, but when we define persistence this should be good solution. We already have xml dependencies in Debrief.

**Comment by IanMayo** [comment]
No, the editor is just the tree table control (like an outline)

**Comment by pecko** [comment]
OK, It will persist to xml similar to Debrief plot. We will open it as tree (Data Manager Editor) or with XML editor. Right?
