### ISSUE TITLE
Preview charts in the Stacked Charts Editor do not reflect the ChartSet orientation

### ISSUE THREAD

**Issue by dinkoivanov** [debrief/limpet#399]
**Steps to reproduce:**
1. open overview.lap
2. right-click on LongContact
3. select Analysis/Show in tactical overview
4. switch to Edit mode
5. change the chartset orientation to Horizontal

**Observed behavior:**
Even though the editor layout is updated after point 5, the preview charts are not refreshed - they still show the time on the horizontal (X) axis.
![image](https://cloud.githubusercontent.com/assets/4459598/18319761/d9592e58-752f-11e6-956c-b0fc62ce0d2e.png)

**Expected behavior:**
Time (shared axis) should be shown on the vertical axis when chartset is in Horizontal Layout. Switching to View mode shows the proper layout:
![image](https://cloud.githubusercontent.com/assets/4459598/18319790/f0762456-752f-11e6-84d9-1fc8a3f0f4a0.png)

**Comment by dinkoivanov** [comment]
@IanMayo this should be fixed in branch 393_update_chart_model, see commit:
https://github.com/debrief/limpet/pull/400/commits/2de09d0cce103bf7838f0be432cb3dc6d59ca2b7

**Comment by IanMayo** [comment]
@dinkoivanov - yes, fixed. Thanks for pointing it out.
