### ISSUE TITLE
Investigate IDataset

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#407]
I've (again) been introduced to the IDataset package, as [promoted](https://projects.eclipse.org/projects/science.january) by the Eclipse Science Working Group.

At a presentation two weeks ago, I was impressed/inspired by a presentation from [Mark Basham](https://www.software.ac.uk/mark-basham)

I'm going to try to get hold of the presentation, to remind myself of what interested me...

There is an initial hurdle.  While **January** (Java Numerical Arrays) was in it's own [repo](https://github.com/eclipse/january), it's now part of a much larger project.  So, you have to clone the January repo, then close all projects other than org.eclipse.january.

There's a page with some examples:
https://github.com/eclipse/january/blob/master/org.eclipse.january.examples/src/org/eclipse/january/examples/dataset/BasicExample.java

I propose we produce some examples to demonstrate we can do the following:
1. include Units of Measurement in the Metadata field
2. ~~produce dataset with two or more arrays (time and distance - speed log, altitude and temperature - weather balloon). Ian: IDataset has reshape to other dimensions, but these assume a common data-type. I don't believe it can handle time (long) vs temperature (double)~~  
**Scrap that:** Let's have one set of measurements per dataset.  So, if the same trial produces timed values of speed and temperature, let's have two time series datasets:  one for speed, and one for temperature.
3. Do some simple calculations (multiplying two data-sets that are, or aren't time-synced). Also, do some "units aware" calculations (such as dividing distance by time, or adding two distances).
4. Create a data structure where 3-d location is a "primary object":  treated as whole, and not 3 separate xyz attributes.  Actually, maybe we should even be storing an OSGeo geometry element.
5. Experiment with storing "predecessor" and "dependent" items in metadata - so we can "flow" changes through the data store.
6. Strategy for just accessing IDataset from the January Repo.  Here is [one](https://github.com/eclipse/january/blob/JANUARY_1_0_0/org.eclipse.january.examples/JanuaryExamples.target), as discussed [here](https://github.com/eclipse/january/issues/4)

I've numbered them for easy reference, but there may be a better logical sequence.

*and a bunch of other things I haven't thought of yet*

## IDataset references:
* [Here](http://www.eclipse.org/community/eclipse_newsletter/2016/november/article1.php) is an article from Tracy Miranda that gives an overview
* The [Getting Started](https://github.com/eclipse/january/tree/master/org.eclipse.january.examples#eclipse-january-examples-and-getting-started) guide is more about accessing/building the code
* [Here](https://github.com/eclipse/january/blob/master/org.eclipse.january.examples/src/org/eclipse/january/examples/dataset/SlicingExamples.java) is an example of Slicing data.  This seems to be the *bread and butter* of many IDataset users.
* The [Dawn Training Package](http://dawnsci.org/assets/pages/developing_dawn/DAWN_Developer_Training_v1.0.pdf) includes introductory steps for IDataset

**Comment by IanMayo** [comment]
Trial of first example developed here:
https://github.com/dinkoivanov/january/commit/a479773ad18f445d70a5a3f8d7dfd8710f0bd318

**Comment by IanMayo** [comment]
Have submitted PR to January project to fix how metadata is stored/retrieved

**Comment by IanMayo** [comment]
So, we appear to have come across two effective show-stoppers:
* an IDataset array can only have a single data-type. This is typically a double, but other versions are available. Significantly, we can't have one row as long values (for timestamp) and others as doubles.  
* an IDataset can only have UoM metadata at the whole-collection level.  We would wish to include UoM for each row within the dataset.  But, @dinkoivanov  may make some progress with an **Axes** metadata descriptor.

**Comment by IanMayo** [comment]
Update for @dinkoivanov : 

the [AxesMetadata](https://github.com/dinkoivanov/january/commit/6ac7f1f54fcf4096f645f94d0e75ffbbaf7f0cbd) example touches on how we can provide "index" arrays to IDatasets.

That still means we have to check if/how we support data of multiple quantity types in a January Dataset (or maybe we don't).  Maybe they're always just one-dimensional.

I think it may be worth growing the AxesMetadata example code to see if we can add UoM to the AxesMetadata type - so we can know if the index/axis is time or distance.

It would also be useful to consider if we can hold multiple types of data in an IDataset:
* we run a vehicle test where we record distance, engine revs, engine temperature, volume of fuel tank, etc.  Do we put all of these into one Dataset (to represent the set of trial data), or do we store them all as separate datasets?

Do you have any thoughts on this? Am I missing something?

**Comment by dinkoivanov** [comment]
@IanMayo I've addressed the issues above [here](https://github.com/dinkoivanov/january/commit/92a7621db052c08b1f62021b9c04484fc08e370d)

- I've added UoM metadata to the axes dataset and then print it back.
- In addition I've explored a way to have multiple types of data in an IDataset. I think the [CompoundDataset](https://github.com/eclipse/january/blob/master/org.eclipse.january/src/org/eclipse/january/dataset/CompoundDataset.java) may be suitable for that.

A specific thing about the CompoundDataset is that it would keep data from all nested datasets in one datatype (it takes the first one in the arguments). In the example that would be "double". Initially that was kind of a stopper, since we were trying to put the timestamps (long) and the measurements in the CompoundDataset. Now we're aware of the AxesMetadata existence and we keep the timestamps in an Axis, which I believe is the proper way. Potentially there could still be an issue if we try to use some kind of a category (discrete data type) dataset. Anyway I don't think that's a major blocker now.

Another effect of the CompoundDataset implementation is that it does not keep the metadata associated with individual datasets - once created, all datasets merge in one multi-dimensional Java array I guess for efficiency. You can see that the compound dataset output print does not include units.
I've explored an approach to address this problem [here](https://github.com/dinkoivanov/january/commit/b890370202ac83c1f15238d3439bf9b74f2e6365). In this approach we keep the UoM metadata for individual datasets in the parent (compound) dataset. This is possible due to the fact that the IDataset allows multiple values of dataset per class, so we call `compoundDataset.addMetadata(datasetXunits)` for each dataset, then we're able to retrieve the list with `compoundDataset.getMetadata(UomMetadata.class)` and iterate it.

Let me know what you think.

**Comment by IanMayo** [comment]
@dinkoivanov - I've had to devise a *temporary* data structure for my current work package (to be replaced by our future Limpet/January data structure). In doing this, I've had chance to have a fresh think about the requirements.

It seems an unnecessary contrivance to need to store multiple types of measurement in one dataset.  I think it's easier for the user to understand *one measurement, one dataset*. (well, in the case of a time series it's two measurements one dataset).  But, we have one independent value, and one dependent value.  

There was merit in a having all datasets that depend on one independent dataset (time recordings) in one grouped object.  But, for the user to manipulate that data (speed, for example) we have to cosmetically break them apart in the UI.  We may as well just store them separately.

So, I'm officially cancelling requirement **2.** in the above set of requirements.

**Comment by IanMayo** [comment]
@dinkoivanov - have been playing with your example code, and have put my findings [here](https://github.com/IanMayo/january/pull/1). 

Sadly the `iadd` operation you use mangles the first input object, but I've found that Maths.add() gives us our desired outcome.  Since the operation returns the modified first input object, it still contains the original UoM metadata - so it mistakenly appears that the operation is able to correctly determine (and assign) the UoM metadata.

I've added some code that attempts to put the correct metadata in the results object.

I've also put some thought into what is required to manipulate non-synced datasets, in an issue [here](https://github.com/eclipse/january/issues/116).  Let's see if the January project can direct us to anywhere that such a practice has been considered before.

There's quite a bit for you to read through/consider.  I'll leave it with you (no rush).

**Comment by IanMayo** [comment]
@dinkoivanov - have had a go at an "axes aware" set of operations, here:
https://github.com/IanMayo/january/pull/1/files#diff-f367a5ac35250220657984bfd22a6cfb

It handles the timestamps in datasets, and how to combine two datasets that have different timestamps.

I'll have a go at a multi-dimensional dataset.

In the future we should also consider operations that are in the same dimension, but different units, such as adding a set of distances in metres to a set of distances in feet.  I'm pretty sure UoM can handle this for us.

We also still have to consider the more general architecture.  I'm really pleased that AxesMetadata allows us to have a dataset indexed in seconds (normal trial) or in metres (weather balloon ascent).  We just have to identify/document the general architecture strategy.

**Comment by IanMayo** [comment]
I've tidied the demonstration code, and offered it up for review here:
https://github.com/eclipse/january/pull/120

I'll start a branch that explores switching to IDataset for the recent task in which I adopted a temporary storage structure.

**Comment by IanMayo** [comment]
We're progressing this in #416
