### ISSUE TITLE
Introduce hierarchical data store

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#41]
We wish to allow the user to store the data in a folder-style hierarchy, to organise the data.

Let's start with just one tier of folders.  Let's defer multiple tiered folders until we have someone to fund it.

We need to keep the API/strategy fairly generic, so that we can use the Store API from within the Debrief context.

So, we need these changes:
- introduce a Folder object that stores a list of ICollections (guess this belongs in core data)
- change ICollection so that a collection can store its folder (with getter/setter)
- change the IStore API so that we always add a new collection to a specific folder
- change the InMemoryStore to store a list of folders
- change the InMemoryStore to allow a new folder to be added
- introduce some unit tests to verify that InMemoryStore works as expected
- change the SampleData class to put the sample data into folders (suggest we have at least _Quantities_ and _Objects_ folders.
- introduce "add folder" to Data Manager
- change the RCP DataModel classes so that they show the list of folders
- introduce drag/drop of collections between folders in the Data Manager

**Comment by IanMayo** [comment]
@dinkoivanov - after myself, you're currently the best understanding of the Limpet object model in the world :-)

I want to "evolve" the way we store data in Limpet, particular to introduce the concept of folders to store collections.

Would you mind having a read through my thoughts in this issue, and providing some feedback / thoughts?

**Comment by dinkoivanov** [comment]
The outlined requirements makes perfect sense to me - simple and clear enough. Perhaps if we look for more flexibility, we can use categories instead. A category can be a simple string (or tag) and each ICollection will provide a list of categories (tags). Then the UI could show categories at first level. This way a Collection could be present in multiple categories. Note that with simple string categories, nesting (multiple tiered folders) won't be possible. Also a thing to consider is if a folder will hold any additional properties (metadata) or simply be a holder object for collections.

**Comment by IanMayo** [comment]
Ok, I'll start on this.
