### ISSUE TITLE
OSX Run problem

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#425]
I have an OSX-specific problem.

The problem started with this commit:
https://github.com/debrief/limpet/pull/416/commits/7e60b65d0aa4bb9b5609786338664bb583c50e9c

Before this commit, the Limpet app runs from Eclipse. 

**Note:** there is a compiler issue with the previous commit - it can be overcome by closing the org.limpet.test project.

This is the previous commit:
https://github.com/debrief/limpet/pull/416/commits/a8cef4cd19589217ad602c4afd4998c48e1308e1

I'd be grateful if you could verify the "breaking" commit also prevents Limpet from running on your machine.  If that's the case, I'd appreciate you investigating what element of the breaking commit causes the problem.

**Comment by theanuradha** [comment]
@IanMayo I narrow down to where it stop loading it is 
it is Geo Tools loading 
**GeoSupport.setCalculator(new GeotoolsCalculator())**;

**Comment by theanuradha** [comment]
https://github.com/debrief/limpet/blob/7e60b65d0aa4bb9b5609786338664bb583c50e9c/info.limpet.rcp/src/info/limpet/rcp/Activator.java#L90

**Comment by theanuradha** [comment]
more investigation narrow it down to geo tool JAI loading 

![image](https://cloud.githubusercontent.com/assets/535713/25570429/d5402020-2e42-11e7-8987-a436f472c05a.png)
![image](https://cloud.githubusercontent.com/assets/535713/25570436/ecd0ccb2-2e42-11e7-8c23-851b9088d7f8.png)

seems **jai_core-1.1.3.jar** and **jvm** it self has same class **javax.media.jai.JAI** and clash at loading

**Comment by theanuradha** [comment]
http://docs.geotools.org/latest/userguide/build/install/jdk.html

**Comment by theanuradha** [comment]
by remove jai_core-1.1.3.jar and added  mlibwrapper_jai-1.1.4-b03.jar and  clibwrapper_jiio-1.1.jar it seems all load in mac. will test this on windows now

**Comment by IanMayo** [comment]
Fixed in #426

**Comment by IanMayo** [comment]
@theanuradha - I'm really pleased you got to the bottom of this.  I didn't know where to start. Could you give me a quick description of how you found the problem?
Cheers,
Ian

**Comment by theanuradha** [comment]
@IanMayo I enable Tracing in Eclipse runtime then I notice it stop at loading plugin with geotool load.
Then I ran in debug mode and once it freeze  it pause so I have stacktrace where it now stack then i dig deep from there on words   
 
![image](https://cloud.githubusercontent.com/assets/535713/25615247/c229a814-2f53-11e7-9f15-d904eaebac98.png)

**Comment by IanMayo** [comment]
Hey - I've never used that Tracing tab.  Thanks for the tip,
Ian
