### ISSUE TITLE
Introduce property editor that has slider

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#47]
Once we have some data that can take a range of values ( #46 ), we should create a custom property editor control that presents a slider.

**Comment by IanMayo** [comment]
@pecko  - this can go some way down your list, it's waiting for me to do #46 first

**Comment by IanMayo** [comment]
@pecko - ok, things are in place now.

The SampleData class now returns the RANGED_SPEED_SINGLETON collection, titled _Ranged Speed Singleton_ in the editor view.

I'd like the property source code to check for a singleton collection (size()==1), and that there is a range present.  If there is, I'd like to use a custom property editor that includes a slider and a text label (to show the current value).

**Comment by IanMayo** [comment]
@pecko - would you mind having a go at this next?

It will be useful for me to prove/demonstrate live data updates.

**Comment by pecko** [comment]
OK. Just a little explanation. You want the following:
when the user selects _Ranged Speed Singleton_, you want me to add slider editor in the Properties view. Right?

Debrief doesn't have an example?

**Comment by pecko** [comment]
BTW
Will try it today later.

**Comment by IanMayo** [comment]
Have pushed a commit with some code comments for you:
https://github.com/debrief/limpet/commit/a46cb954cc9b4a804c00f6b46b3c3a49e22f7ab1

Debrief does have a "BoundedIntegerHelper" set of classes, if I remember correctly.  I think that used a Stepper control.  But, this will use an slider.

**Comment by pecko** [comment]
It's OK. I will find. It is important that you mean an editor in the Properties view.

**Comment by pecko** [comment]
@IanMayo 
I have created the issue47 branch (https://github.com/pecko/limpet/tree/issue47) in order to you can review.
The feature is mostly copied and adapted from Debrief.
There are one issue:
- setting minimum value is ignored - SWT always allows to set values from 0-maximum
  Because of that I don't create the PR. I have to investigate the issue.

**Comment by IanMayo** [comment]
Sad to hear about the setMinimum problem. Very surprising.

Are you able to fire "modified" events, so that the object value gets set as the slider is dragged?

Currently, the object value only gets set when the control loses focus.

**Comment by IanMayo** [comment]
Fixed the "setMinimum" problem - you need to set the maximum value first :-)

The slider control starts off with min-0, max=100.  As you set min/max, it checks that it's less than/greather than the current max/min value.

**Comment by pecko** [comment]
Checking ...

**Comment by pecko** [comment]
It works. The PR: https://github.com/debrief/limpet/pull/92

**Comment by pecko** [comment]
Fixed.

**Comment by IanMayo** [comment]
@pecko  

```
Are you able to fire "modified" events, so that the
 object value gets set as the slider is dragged?

Currently, the object value only gets set when
the control loses focus.
```

**Comment by pecko** [comment]
Will try.

**Comment by IanMayo** [comment]
Peco, don't worry about the live updates. In the eclipse ui standard yesterday I read that property editors weren't meant to send the update until the user orders enter or navigates away.

I think the correct way to fire live updates is to add a range editor view. I'll add it as a new issue.

**Comment by pecko** [comment]
We can close this issue. Right?
