### ISSUE TITLE
Fix compiler warnings

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#53]
The code to create the RCP application has introduced some compiler warnings.

Peco is going fix warnings as possible and add SuppresWarnings for remaining ones.

**Comment by pecko** [comment]
I have to use SuppressWarnings for all API restriction warnings as follows;

```
Discouraged access: The constructor 'AboutInfo(IProduct)' is not API (restriction on required library '/home/snpe/Workspaces/workspace-limpet/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/plugins/org.eclipse.ui.ide_3.8.2.v20121106-170106.jar')  ApplicationWorkbenchWindowAdvisor.java  /info.limpet.rcp/src/info/limpet/rcp/product    line 574    Java Problem
```

Will try to fix other.

**Comment by pecko** [comment]
I have also suppressed deprecated methods/fields. These artifacts are good tested and changing them could introduce a bug.
