### ISSUE TITLE
Introduce location dataset

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#6]
It will be important to include fundamental support for location.

Create Temporal and Non-Temporal collections that contain location - with appropriate top level interfaces.

Note: I'm unsure whether we will extend QuantityCollection or ObjectCollection.

**Comment by IanMayo** [comment]
Initial version created: https://github.com/debrief/limpet/blob/4b54f3602297ef7cb3bec699486fdf6db3d01568/info.limpet/src/info/limpet/data/impl/samples/StockTypes.java#L106

Using location "placeholder". We should probably incorporate GeoTools, then use a GeoTools location object.

@pecko - could you add sufficient jars/libs for us to instantiate an TemporalObjectCollection with GeoTools "Geometry" type:

```
locations = new TemporalObjectCollection<Geometry>();
```

thx.

**Comment by pecko** [comment]
I can do it, but, IMO< better solution is that we use geotools from debrief (just copy it for now). 
Since Debrief depends on Limpet we will later just remove this plugins from Debrief and acquire it from Limpet.

Otherwise, we will have two geotools libraries that could be an issue for maintenance.

@IanMayo 
WDYT?

**Comment by IanMayo** [comment]
Yes, that's a sensible solution.

But, I need Limpet to run standalone, without Debrief.  Temporarily, let's have two geotools libraries.

**Comment by pecko** [comment]
Right. At the end, Geotools will be in Limpet repository (part of some limpet feature), but, for now, it will also be in Debrief.
When we create Limpet p2 repository (update site), we will add it to Debrief's target platform and remove geotools from main Debrief repo.

**Comment by IanMayo** [comment]
Let's keep the duplicate copy for now.  GeoTools seems fundamental to Debrief. Limpet seems an optional add-on.

**Comment by pecko** [comment]
OK. I will keep the same name/provider/version.

**Comment by pecko** [comment]
I have created the info.limpet.geotools plugin that includes only gt-opengis-14.0.jar and dependencies.
The Geotools 14.0 is the latest stable version of geotools.

There is a test that create 

```
locations = new TemporalObjectCollection<Geometry>();
```

The PR:https://github.com/debrief/limpet/pull/98

**Comment by pecko** [comment]
I have applied the PR.

@IanMayo 
If you want add some other geotools library or change version, please, open a new issue.
