### ISSUE TITLE
Update perspective layout

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#60]
@pecko - could you re-arrange the Limpet perspective so we have this layout:

![limpetarrangement](https://cloud.githubusercontent.com/assets/1108513/10163298/c99076f6-66a9-11e5-8edc-a365b2fde759.png)

[the XY Plot is new, I'll push it to master shortly]

**Comment by pecko** [comment]
@IanMayo 

I have playing a little with this perspective and can't do it even manually.
Could we replace editor area(Data Manager Editor) with the Properties view?
If no and you got it manually, could you please do the following:
- create layout as on screenshot
- save perspective with name LimpetTest
- close Limpet RCP
- send me the <YOUR_LIMPET_WORKSPACE>/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.workbench.prefs

**Comment by pecko** [comment]
I have playing with this prety long and the following is what i made programmaticaly:

![image](https://cloud.githubusercontent.com/assets/534584/10208160/97770b0c-67d1-11e5-86df-24f2a63fcf3e.png)

**Comment by pecko** [comment]
The PR: https://github.com/debrief/limpet/pull/86

Maybe, it isn't perfect; please reopen in this case.
