### ISSUE TITLE
Generate location collections

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#63]
We're going to have lots of location datasets in Debrief.

Once @pecko has introduced the GeoTools libraries, Ian should create some location datasets to work with.

Suggest these form a vessel travelling a loop, something like 2 miles north, turn to the east, then the south, then the west, then carry on for 2 miles.

**Comment by IanMayo** [comment]
@pecko  - I've been working on this in the issue63_locations branch.

But, I've  got stuck = the allTests suite is failing.  I'm pretty sure that it's because we define Unit in both our Limpet libs and the GeoTools libs.

I'm keen that we use the up-to-date Unit object from UoM in our Limpet implementation.  But, I'm stuck on how to resolve this.  

_Yes, I realise it's loosely related to your warnings yesterday about incorporating two copies of libraries, but believe this is an unrelated instance._

Are you able to fix the build so that the code works?  If not, I guess the best strategy is to define ILocation as an interface that has a Limpet implementation (using uom) and a separate Debrief implementation (using geotools).

Any other thoughts/suggestions?

I'd appreciate you pulling this to the top of your list please - it's important that I support location, and need to demonstrate how it works late next week.

**Comment by pecko** [comment]
@IanMayo 

You want me to try to build the issue63_locations branch and fix an issue if exists. Right?

**Comment by IanMayo** [comment]
yes, please.

**Comment by pecko** [comment]
Working on that now...

**Comment by pecko** [comment]
> But, I've got stuck = the allTests suite is failing. I'm pretty sure that it's because we define Unit in both our Limpet libs and the GeoTools libs.

What Unit you mean? AFAICS, here aren't any same libs in these plugins.

**Comment by pecko** [comment]
I have created the issue63-jsr257 branch based on the issue63_locations branch.
Will push periodical.

**Comment by pecko** [comment]
These two libraries are different too much. I stop this. Will try to isolate jsr-275 in geotools. Will also stop if it isn't possible quickly.

**Comment by pecko** [comment]
It isn't possible. I will review if it's hard to replace jsr-275 with jsr-363 in geotools.

**Comment by IanMayo** [comment]
I'm pretty sure @dinkoivanov & I could switch to JSR-275.   We'll have a look on Monday.  Could you produce a branch with JSR-363 removed, that includes GeoTools?  To prove GeoTools integration you would create a GeoTools point (or location).

**Comment by pecko** [comment]
OK.
I will create branch without JSR-363 and with JSR-275. 
It will not compile.
I will also create a geotools example in test plugin that should work.
FYI See https://osgeo-org.atlassian.net/browse/GEO-190. It seems that main issue is license for JSR-363.

**Comment by pecko** [comment]
Additional.

I will create a new branch starting from master.

**Comment by pecko** [comment]
I have created the issue63 branch: https://github.com/pecko/limpet/tree/issue63

The branch doesn't include jsr-363. It includes jsr-257 in the geotools plugin. You can access it from info.limpet as well as some plugin that depends on info.limpet (info.impet.rcp, info.limpet.test...)

info.limpet, info.limpet.rcp and info.limpet.test have compile errors because jsr-363 (unit-api, unit-ri) is removed.

There is the info.limpet.data.TestGeotoolsGeometry.testCreatePoint() in the info.limpet.test that creates a point. This test pass no matter these plugin don't compile.

I have had an issue with the gt-jts-wrapper library (geotools plugin). The above mentioned test fails with this exception:

```
Exception in thread "main" java.lang.IllegalArgumentException: DirectPosition cannot have a null CRS
    at org.geotools.geometry.jts.spatialschema.geometry.DirectPositionImpl.setCRS(DirectPositionImpl.java:178)
    at org.geotools.geometry.jts.spatialschema.geometry.DirectPositionImpl.<init>(DirectPositionImpl.java:149)
    at org.geotools.geometry.jts.spatialschema.geometry.primitive.PrimitiveFactoryImpl.createDirectPosition(PrimitiveFactoryImpl.java:111)
    at org.geotools.geometry.jts.spatialschema.geometry.primitive.PrimitiveFactoryImpl.createPoint(PrimitiveFactoryImpl.java:121)
    at org.geotools.geometry.GeometryBuilder.createPoint(GeometryBuilder.java:310)
    at org.geotools.geometry.GeometryBuilder.createPoint(GeometryBuilder.java:285)
    at org.geotools.demo.geometry.GeometryExample.main(GeometryExample.java:213)
```

I think that gt-jts-wrapper has a bug. I'm not sure why you include it. We don't use it in Debrief. I have added the gt-geometry library that enable creating point in the mentioned test. We have to find issue if it is obliged.

I haven't created the PR because the branch don't compile.

**Comment by IanMayo** [comment]
@pecko - have incorporated the GeoTools libs.

I'm having trouble with class not found.  I've created a test that triggers the class not found, and pushed it into the branch **issue63_calculator**.

Would you mind having a look at it, when you get chance?

cheers,
Ian

**Comment by pecko** [comment]
@IanMayo 
Of course. I will do it during day (very soon, probably). The issue63_calculator branch includes the latest jsr_275 work. Right?

**Comment by IanMayo** [comment]
yes

**Comment by pecko** [comment]
Fixed with https://github.com/pecko/limpet/commit/2899892f249d14af764b62f45ab5d61e7798db41

**Comment by IanMayo** [comment]
done.

**Comment by pecko** [comment]
Did you apply something to master related to this issue?

**Comment by IanMayo** [comment]
aah no, I've still got it in a branch. But, I'm happy that we've overcome the issue.

**Comment by pecko** [comment]
I asked because it could maybe affect #22

**Comment by IanMayo** [comment]
Sure. Will push/merge my progress.
